defmodule AuroraMeterExampleAiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :aurora_meter_example_ai

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_aurora_meter_example_ai_key",
    signing_salt: "RKKxoOm9",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :aurora_meter_example_ai,
    gzip: not code_reloading?,
    only: AuroraMeterExampleAiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :aurora_meter_example_ai
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # The Stripe webhook, mounted here and not in the router.
  #
  # Stripe signs the RAW body. `Plug.Parsers` below consumes it, after which
  # `Plug.Conn.read_body/2` answers `{:ok, "", conn}` and every signature
  # check fails. A router `forward` is always after the parsers, so it cannot
  # be the mount point however tempting it looks. See
  # `AuroraMeterExampleAiWeb.Pro.WebhookMount`.
  #
  # The `if` is evaluated at compile time, so in the core profile this plug is
  # not in the endpoint's pipeline at all: a request to /webhooks/stripe there
  # reaches the router and 404s, which is the honest answer for an application
  # with no billing in it.
  if AuroraMeterExampleAi.Pro.available?() do
    plug AuroraMeterExampleAiWeb.Pro.WebhookMount
  end

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AuroraMeterExampleAiWeb.Router
end
