defmodule AuroraMeter.Migration do
  @moduledoc """
  Creates and drops the Aurora Meter core tables, in versions.

  A host migration delegates here, so schema changes ship as new versions of
  this module rather than as edits to the host's migration file. Every version
  is idempotent (`create_if_not_exists`), so `up/1` can safely run from version 1
  each time.

  Fresh install (generated by `mix aurora_meter.gen.migration`):

      def up, do: AuroraMeter.Migration.up()
      def down, do: AuroraMeter.Migration.down()

  Upgrading an existing install to a newer schema version, add a migration that
  runs only the new versions:

      def up, do: AuroraMeter.Migration.up(from: 2)
      def down, do: AuroraMeter.Migration.down(to: 2)

  ## Versions

    * **1** — `aurora_meter_subscriptions`, `aurora_meter_counters`,
      `aurora_meter_events`
    * **2** — `aurora_meter_history` (UTC day buckets for `AuroraMeter.history/3`)
  """

  @latest 2

  @doc """
  The newest schema version this release of Aurora Meter knows about.

  ## Examples

      iex> AuroraMeter.Migration.latest_version()
      2

  """
  @spec latest_version() :: pos_integer()
  def latest_version, do: @latest

  @doc """
  Runs the `up` step of every version from `:from` (default 1) to `:version`
  (default the latest).
  """
  @spec up(keyword()) :: :ok
  def up(opts \\ []) do
    from = Keyword.get(opts, :from, 1)
    to = Keyword.get(opts, :version, @latest)
    Enum.each(from..to//1, &module(&1).up())
    :ok
  end

  @doc """
  Runs the `down` step of every version from `:version` (default the latest)
  down to `:to` (default 1).
  """
  @spec down(keyword()) :: :ok
  def down(opts \\ []) do
    from = Keyword.get(opts, :version, @latest)
    to = Keyword.get(opts, :to, 1)
    Enum.each(from..to//-1, &module(&1).down())
    :ok
  end

  @spec module(pos_integer()) :: module()
  defp module(version) when version in 1..@latest//1,
    do: Module.concat(__MODULE__, "V#{version}")

  defp module(version) do
    raise ArgumentError,
          "unknown Aurora Meter migration version #{inspect(version)} (latest is #{@latest})"
  end
end

defmodule AuroraMeter.Migration.V1 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_subscriptions, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :plan_id, :string, null: false
      add :status, :string, null: false, default: "active"
      add :provider, :string
      add :provider_customer_id, :string
      add :provider_subscription_id, :string
      add :current_period_start, :utc_datetime
      add :current_period_end, :utc_datetime
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_subscriptions, [:tenant_key])

    create_if_not_exists table(:aurora_meter_counters, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :period_start, :utc_datetime, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_counters, [
                           :tenant_key,
                           :feature,
                           :period_start
                         ])

    create_if_not_exists table(:aurora_meter_events, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :quantity, :integer, null: false, default: 1
      add :metadata, :map, null: false, default: fragment("'{}'::jsonb")
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create_if_not_exists index(:aurora_meter_events, [:tenant_key, :feature, :inserted_at])

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_events)
    drop_if_exists table(:aurora_meter_counters)
    drop_if_exists table(:aurora_meter_subscriptions)
    :ok
  end
end

defmodule AuroraMeter.Migration.V2 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_history, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :bucket_kind, :string, null: false, default: "day"
      add :bucket_start, :date, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(
                           :aurora_meter_history,
                           [:tenant_key, :feature, :bucket_kind, :bucket_start],
                           name: :aurora_meter_history_bucket_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_history)
    :ok
  end
end
