defmodule AuroraMeter.Migration do
  @moduledoc """
  Creates and drops the Aurora Meter core tables, in versions.

  A host migration delegates here, so schema changes ship as new versions of
  this module rather than as edits to the host's migration file. Every version
  is idempotent (`create_if_not_exists`), so `up/1` can safely run from version 1
  each time.

  Fresh install (generated by `mix aurora_meter.gen.migration`):

      def up, do: AuroraMeter.Migration.up()
      def down, do: AuroraMeter.Migration.down()

  Upgrading an existing install to a newer schema version, add a migration that
  runs only the new versions:

      def up, do: AuroraMeter.Migration.up(from: 3)
      def down, do: AuroraMeter.Migration.down(to: 3)

  ## Versions

    * **1** — `aurora_meter_subscriptions`, `aurora_meter_counters`,
      `aurora_meter_events`
    * **2** — `aurora_meter_history` (UTC day buckets for `AuroraMeter.history/3`)
    * **3** — `aurora_meter_credit_balances`, `aurora_meter_credit_transactions`
      (the prepaid ledger behind `AuroraMeter.Credits`)
    * **4** — `promotional_after` on `aurora_meter_credit_transactions`, so the
      promotional figure can be rebuilt from the log like `balance` and `held`
    * **5** — a partial index on open holds, so the sweep for reservations
      nothing will ever close does not scan the whole ledger
    * **6** — `aurora_meter_flush_receipts`, committed atomically with counter
      and history deltas to deduplicate retries after uncertain writes
  """

  @latest 6

  @doc """
  The newest schema version this release of Aurora Meter knows about.

  ## Examples

      iex> AuroraMeter.Migration.latest_version()
      6

  """
  @spec latest_version() :: pos_integer()
  def latest_version, do: @latest

  @doc """
  Runs the `up` step of every version from `:from` (default 1) to `:version`
  (default the latest).
  """
  @spec up(keyword()) :: :ok
  def up(opts \\ []) do
    from = Keyword.get(opts, :from, 1)
    to = Keyword.get(opts, :version, @latest)
    Enum.each(from..to//1, &module(&1).up())
    :ok
  end

  @doc """
  Runs the `down` step of every version from `:version` (default the latest)
  down to `:to` (default 1).
  """
  @spec down(keyword()) :: :ok
  def down(opts \\ []) do
    from = Keyword.get(opts, :version, @latest)
    to = Keyword.get(opts, :to, 1)
    Enum.each(from..to//-1, &module(&1).down())
    :ok
  end

  @spec module(pos_integer()) :: module()
  defp module(version) when version in 1..@latest//1,
    do: Module.concat(__MODULE__, "V#{version}")

  defp module(version) do
    raise ArgumentError,
          "unknown Aurora Meter migration version #{inspect(version)} (latest is #{@latest})"
  end
end

defmodule AuroraMeter.Migration.V1 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_subscriptions, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :plan_id, :string, null: false
      add :status, :string, null: false, default: "active"
      add :provider, :string
      add :provider_customer_id, :string
      add :provider_subscription_id, :string
      add :current_period_start, :utc_datetime
      add :current_period_end, :utc_datetime
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_subscriptions, [:tenant_key])

    create_if_not_exists table(:aurora_meter_counters, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :period_start, :utc_datetime, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_counters, [
                           :tenant_key,
                           :feature,
                           :period_start
                         ])

    create_if_not_exists table(:aurora_meter_events, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :quantity, :integer, null: false, default: 1
      add :metadata, :map, null: false, default: fragment("'{}'::jsonb")
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create_if_not_exists index(:aurora_meter_events, [:tenant_key, :feature, :inserted_at])

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_events)
    drop_if_exists table(:aurora_meter_counters)
    drop_if_exists table(:aurora_meter_subscriptions)
    :ok
  end
end

defmodule AuroraMeter.Migration.V2 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_history, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :bucket_kind, :string, null: false, default: "day"
      add :bucket_start, :date, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(
                           :aurora_meter_history,
                           [:tenant_key, :feature, :bucket_kind, :bucket_start],
                           name: :aurora_meter_history_bucket_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_history)
    :ok
  end
end

defmodule AuroraMeter.Migration.V5 do
  @moduledoc false

  import Ecto.Migration

  # An index for `pending_holds/1`.
  #
  # A host looking for reservations nothing will ever close asks for every
  # open hold older than a cutoff, and there was no index that led with `kind`
  # or `status` — so on a cron that runs every five minutes, the question was
  # a sequential scan of an append-only table that only grows. Partial, because
  # a pending hold is a vanishing fraction of the log: everything else has been
  # settled or released.
  @spec up() :: :ok
  def up do
    create_if_not_exists index(
                           :aurora_meter_credit_transactions,
                           [:inserted_at],
                           where: "kind = 'hold' AND status = 'pending'",
                           name: :aurora_meter_pending_holds_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists index(:aurora_meter_credit_transactions, [:inserted_at],
                     name: :aurora_meter_pending_holds_index
                   )

    :ok
  end
end

defmodule AuroraMeter.Migration.V4 do
  @moduledoc false

  import Ecto.Migration

  # `promotional_after`, so the promotional figure can be rebuilt from the log
  # like `balance` and `held` already can.
  #
  # It is not a running sum of the entries: promotional credit is consumed
  # before paid credit and is clamped to the balance after every entry, so the
  # figure moves for reasons no single `amount` explains. With no snapshot the
  # row on `aurora_meter_credit_balances` was the only copy, and nothing could
  # tell a clamp from a bug.
  @spec up() :: :ok
  def up do
    alter table(:aurora_meter_credit_transactions) do
      add_if_not_exists :promotional_after, :bigint
    end

    :ok
  end

  @spec down() :: :ok
  def down do
    alter table(:aurora_meter_credit_transactions) do
      remove_if_exists :promotional_after, :bigint
    end

    :ok
  end
end

defmodule AuroraMeter.Migration.V3 do
  @moduledoc false

  import Ecto.Migration

  # ADR: amounts are signed bigints in micro-dollars (1e-6 USD) so the ledger can
  # carry per-token AI prices (fractions of a cent) without floats or Decimal on
  # the hot path; `AuroraMeter.Credits.Money` converts at the edges. The
  # transactions table is append-only and every row snapshots `balance_after`
  # / `held_after`, so the balance can be audited or rebuilt from the log.
  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_credit_balances, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :balance, :bigint, null: false, default: 0
      add :held, :bigint, null: false, default: 0
      add :promotional, :bigint, null: false, default: 0
      add :low_balance_threshold, :bigint
      add :currency, :string, null: false, default: "usd"
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_credit_balances, [:tenant_key])

    create_if_not_exists table(:aurora_meter_credit_transactions, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :kind, :string, null: false
      add :category, :string
      add :amount, :bigint, null: false
      add :held_delta, :bigint, null: false, default: 0
      add :balance_after, :bigint, null: false
      add :held_after, :bigint, null: false
      add :reference, :string
      add :status, :string
      add :settled_amount, :bigint
      add :expires_at, :utc_datetime
      add :expired_at, :utc_datetime
      add :metadata, :map, null: false, default: fragment("'{}'::jsonb")
      add :inserted_at, :utc_datetime_usec, null: false
    end

    # One grant / hold / debit per reference: the idempotency key for retries.
    create_if_not_exists unique_index(
                           :aurora_meter_credit_transactions,
                           [:kind, :reference],
                           where: "reference IS NOT NULL",
                           name: :aurora_meter_credit_transactions_kind_reference_index
                         )

    create_if_not_exists index(:aurora_meter_credit_transactions, [:tenant_key, :inserted_at])

    # Promotional grants still waiting to expire — what `Credits.expire_due/1` scans.
    create_if_not_exists index(
                           :aurora_meter_credit_transactions,
                           [:expires_at],
                           where:
                             "kind = 'grant' AND category = 'promotional' AND expired_at IS NULL",
                           name: :aurora_meter_credit_transactions_promo_expiry_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_credit_transactions)
    drop_if_exists table(:aurora_meter_credit_balances)
    :ok
  end
end
