defmodule AuroraMeter.Migration do
  @moduledoc """
  Creates and drops the Aurora Meter core tables, in versions.

  A host migration delegates here, so schema changes ship as new versions of
  this module rather than as edits to the host's migration file. Every version
  is idempotent (`create_if_not_exists`), so `up/1` can safely run from version 1
  each time.

  Fresh install (generated by `mix aurora_meter.gen.migration`):

      def up, do: AuroraMeter.Migration.up(from: 1, version: 9, concurrently: false)
      def down, do: AuroraMeter.Migration.down(version: 9, to: 1, confirm_data_loss: true)

  Upgrading an existing install to a newer schema version, add a migration that
  runs only the new versions, pinned at both ends so that two databases built
  from the same migration files end up with the same schema whenever they are
  built:

      def up, do: AuroraMeter.Migration.up(from: 3, version: 3)
      def down, do: AuroraMeter.Migration.down(version: 3, to: 3)

  ## Versions

    * **1** — `aurora_meter_subscriptions`, `aurora_meter_counters`,
      `aurora_meter_events`
    * **2** — `aurora_meter_history` (UTC day buckets for `AuroraMeter.history/3`)
    * **3** — `aurora_meter_credit_balances`, `aurora_meter_credit_transactions`
      (the prepaid ledger behind `AuroraMeter.Credits`)
    * **4** — `promotional_after` on `aurora_meter_credit_transactions`, so the
      promotional figure can be rebuilt from the log like `balance` and `held`
    * **5** — a partial index on open holds, so the sweep for reservations
      nothing will ever close does not scan the whole ledger
    * **6** — `aurora_meter_flush_receipts`, committed atomically with counter
      and history deltas to deduplicate retries after uncertain writes
    * **7**: durable event identity on `aurora_meter_events` (`event_id`,
      `payload_hash`, `occurred_at`, `period_start`, `kind`, `dimensions`, plan
      attribution and a `seq` identity column), `quantity` widened to `bigint`,
      and the new `aurora_meter_event_totals` and `aurora_meter_checkpoints`
      tables. Additive: an 0.4.x node keeps writing events through it. Run
      `mix aurora_meter.events.backfill` after it and before version 8
    * **8**: the unique index on `(tenant_key, event_id)`, built
      `CONCURRENTLY`, and `event_id`, `payload_hash` and `occurred_at`
      promoted to `NOT NULL` behind it, which is what makes "one identity,
      one fact" a guarantee of the database rather than a convention of the
      application. It also validates the constraints version 7 added
      `NOT VALID`. **It must be generated into a host migration of its own**,
      carrying `@disable_ddl_transaction true` and
      `@disable_migration_lock true`, because Postgres refuses
      `CREATE INDEX CONCURRENTLY` inside a transaction block. `up/1` raises
      `AuroraMeter.Migration.ConcurrentVersionError` rather than let it share
      a file. A fresh install passes `concurrently: false` and builds the
      index inside the transaction, which is right for a table with no rows
      in it
    * **9**: the credit lot engine's tables (`aurora_meter_credit_lots`,
      `aurora_meter_credit_allocations`, `aurora_meter_credit_recurrences`),
      `debt`, `expired`, `lots_enabled_at`, `projection_checked_at` and
      `low_balance_crossing_id` on `aurora_meter_credit_balances` with the
      `held >= 0` and `promotional >= 0` checks the changeset has always
      claimed, and `seq`, `updated_at` and `hold_transaction_id` on
      `aurora_meter_credit_transactions`. `seq` is a
      `GENERATED ALWAYS AS IDENTITY` column and it replaces `inserted_at` as
      the ledger's ordering key: a wall clock steps backwards and an identity
      cannot. Additive and writes no data; wallets stay on the legacy writer
      until `mix aurora_meter.credits.migrate_lots` sets `lots_enabled_at`

  ## The schema marker

  From version 7 on, a successful version writes the version it reached into
  `aurora_meter_checkpoints` under the name `"schema:core"`:

      AuroraMeter.Checkpoints.get("schema:core").cursor["version"]

  Absence of the row means the database is below version 7, because the table
  itself arrives with version 7.

  ## Options

    * `:from` / `:version`: the inclusive range `up/1` runs (`:version` / `:to`
      for `down/1`). Always pin both ends in a generated file.
    * `:concurrently` (`up/1`, default `true`): whether a concurrent version
      may use `CREATE INDEX CONCURRENTLY`. `false` builds the index inside the
      migration's transaction, which is what a fresh install wants and what an
      install with a small events table can afford.
    * `:validate_checks` (`up/1`, default `true`): whether to prove the
      constraints version 7 added `NOT VALID` against the existing rows.
    * `:lock_timeout` (`up/1`, default `"5s"`): the `lock_timeout` version 7
      sets around its `ALTER TABLE`, so a stuck lock fails fast rather than
      queueing every query on `aurora_meter_events` behind it.
    * `:confirm_data_loss` (`down/1`, default `false`): required to run the
      `down` of a version that destroys a commercial fact.
  """

  # `flush/0` is a macro whose expansion also calls `direction/0`, so both have
  # to be imported for it to resolve in this module.
  import Ecto.Migration, only: [flush: 0, direction: 0]

  alias AuroraMeter.Migration.ConcurrentVersionError
  alias AuroraMeter.Migration.DataLossError

  @latest 9

  # A version that cannot run inside a DDL transaction, because it creates an
  # index concurrently. It needs its own host migration file carrying
  # `@disable_ddl_transaction true` and `@disable_migration_lock true`.
  @concurrent_versions [8]

  # A version whose `down` destroys a commercial fact rather than an index or a
  # nullable column. 11b adds the pre-existing versions 1, 3 and 4.
  #
  # Version 9 is on it because its `down` drops the credit lots and their
  # allocations, which are the provenance of every micro-dollar a cut-over
  # wallet holds, and takes `debt` with them.
  @data_loss_versions [7, 9]

  # The first version that writes the marker, which is also the version that
  # creates the table it lives in.
  @marked_from 7

  @marker_sql """
  INSERT INTO aurora_meter_checkpoints (name, cursor, counts, state, updated_at)
  VALUES ('schema:core', jsonb_build_object('version', $1::integer), '{}'::jsonb, 'applied',
          (clock_timestamp() AT TIME ZONE 'UTC'))
  ON CONFLICT (name) DO UPDATE
    SET cursor = jsonb_set(aurora_meter_checkpoints.cursor, '{version}', to_jsonb($1::integer)),
        state = 'applied',
        updated_at = (clock_timestamp() AT TIME ZONE 'UTC')
  """

  @doc """
  The newest schema version this release of Aurora Meter knows about.

  ## Examples

      iex> AuroraMeter.Migration.latest_version()
      9

  """
  @spec latest_version() :: pos_integer()
  def latest_version, do: @latest

  @doc """
  The versions that must run in their own host migration, outside a DDL
  transaction.

  ## Examples

      iex> is_list(AuroraMeter.Migration.concurrent_versions())
      true

  """
  @spec concurrent_versions() :: [pos_integer()]
  def concurrent_versions, do: @concurrent_versions

  @doc """
  The versions whose `down` destroys a commercial fact and so needs
  `confirm_data_loss: true`.

  ## Examples

      iex> 7 in AuroraMeter.Migration.data_loss_versions()
      true

  """
  @spec data_loss_versions() :: [pos_integer()]
  def data_loss_versions, do: @data_loss_versions

  @doc """
  Runs the `up` step of every version from `:from` (default 1) to `:version`
  (default the latest). See the module documentation for the options.

  Raises `AuroraMeter.Migration.ConcurrentVersionError` when the range holds a
  concurrent version alongside another version and `concurrently: false` was
  not passed.
  """
  @spec up(keyword()) :: :ok
  def up(opts \\ []) do
    from = Keyword.get(opts, :from, 1)
    to = Keyword.get(opts, :version, @latest)
    versions = Enum.to_list(from..to//1)

    guard_concurrent!(versions, Keyword.get(opts, :concurrently, true))

    Enum.each(versions, fn version ->
      run(version, :up, opts)
      mark(version)
    end)

    :ok
  end

  @doc """
  Runs the `down` step of every version from `:version` (default the latest)
  down to `:to` (default 1).

  Raises `AuroraMeter.Migration.DataLossError` when the range holds a version
  whose `down` destroys a commercial fact and `confirm_data_loss: true` was not
  passed.
  """
  @spec down(keyword()) :: :ok
  def down(opts \\ []) do
    from = Keyword.get(opts, :version, @latest)
    to = Keyword.get(opts, :to, 1)
    versions = Enum.to_list(from..to//-1)

    guard_data_loss!(versions, Keyword.get(opts, :confirm_data_loss, false))

    Enum.each(versions, fn version ->
      run(version, :down, opts)
      unmark(version)
    end)

    :ok
  end

  defp guard_concurrent!(versions, concurrently) do
    concurrent = Enum.filter(versions, &(&1 in @concurrent_versions))

    if concurrently and concurrent != [] and length(versions) > 1 do
      raise ConcurrentVersionError, versions: versions, concurrent: concurrent
    end

    :ok
  end

  defp guard_data_loss!(versions, confirmed) do
    destructive = Enum.filter(versions, &(&1 in @data_loss_versions))

    if not confirmed and destructive != [] do
      raise DataLossError, versions: versions, destructive: destructive
    end

    :ok
  end

  # Versions 1 to 6 are published and their modules take no arguments. Editing
  # one is editing history, so the dispatcher adapts to them rather than the
  # other way round.
  defp run(version, direction, opts) when version >= @marked_from do
    apply(module(version), direction, [opts])
  end

  defp run(version, direction, _opts) do
    apply(module(version), direction, [])
  end

  # Written after the version, on the version's own connection, so a database
  # that reached 7 and failed on 8 says 7 rather than nothing.
  defp mark(version) when version >= @marked_from do
    flush()
    Ecto.Migration.repo().query!(@marker_sql, [version])
    :ok
  end

  defp mark(_version), do: :ok

  # After a successful `down` of version n the database is at n - 1. Version 7
  # takes the checkpoints table with it, so there is nothing left to write.
  defp unmark(version) when version > @marked_from do
    flush()
    Ecto.Migration.repo().query!(@marker_sql, [version - 1])
    :ok
  end

  defp unmark(_version), do: :ok

  @spec module(pos_integer()) :: module()
  defp module(version) when version in 1..@latest//1,
    do: Module.concat(__MODULE__, "V#{version}")

  defp module(version) do
    raise ArgumentError,
          "unknown Aurora Meter migration version #{inspect(version)} (latest is #{@latest})"
  end
end

defmodule AuroraMeter.Migration.V1 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_subscriptions, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :plan_id, :string, null: false
      add :status, :string, null: false, default: "active"
      add :provider, :string
      add :provider_customer_id, :string
      add :provider_subscription_id, :string
      add :current_period_start, :utc_datetime
      add :current_period_end, :utc_datetime
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_subscriptions, [:tenant_key])

    create_if_not_exists table(:aurora_meter_counters, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :period_start, :utc_datetime, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_counters, [
                           :tenant_key,
                           :feature,
                           :period_start
                         ])

    create_if_not_exists table(:aurora_meter_events, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :quantity, :integer, null: false, default: 1
      add :metadata, :map, null: false, default: fragment("'{}'::jsonb")
      add :inserted_at, :utc_datetime_usec, null: false
    end

    create_if_not_exists index(:aurora_meter_events, [:tenant_key, :feature, :inserted_at])

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_events)
    drop_if_exists table(:aurora_meter_counters)
    drop_if_exists table(:aurora_meter_subscriptions)
    :ok
  end
end

defmodule AuroraMeter.Migration.V2 do
  @moduledoc false

  import Ecto.Migration

  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_history, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :feature, :string, null: false
      add :bucket_kind, :string, null: false, default: "day"
      add :bucket_start, :date, null: false
      add :value, :bigint, null: false, default: 0
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(
                           :aurora_meter_history,
                           [:tenant_key, :feature, :bucket_kind, :bucket_start],
                           name: :aurora_meter_history_bucket_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_history)
    :ok
  end
end

defmodule AuroraMeter.Migration.V5 do
  @moduledoc false

  import Ecto.Migration

  # An index for `pending_holds/1`.
  #
  # A host looking for reservations nothing will ever close asks for every
  # open hold older than a cutoff, and there was no index that led with `kind`
  # or `status`: so on a cron that runs every five minutes, the question was
  # a sequential scan of an append-only table that only grows. Partial, because
  # a pending hold is a vanishing fraction of the log: everything else has been
  # settled or released.
  @spec up() :: :ok
  def up do
    create_if_not_exists index(
                           :aurora_meter_credit_transactions,
                           [:inserted_at],
                           where: "kind = 'hold' AND status = 'pending'",
                           name: :aurora_meter_pending_holds_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists index(:aurora_meter_credit_transactions, [:inserted_at],
                     name: :aurora_meter_pending_holds_index
                   )

    :ok
  end
end

defmodule AuroraMeter.Migration.V4 do
  @moduledoc false

  import Ecto.Migration

  # `promotional_after`, so the promotional figure can be rebuilt from the log
  # like `balance` and `held` already can.
  #
  # It is not a running sum of the entries: promotional credit is consumed
  # before paid credit and is clamped to the balance after every entry, so the
  # figure moves for reasons no single `amount` explains. With no snapshot the
  # row on `aurora_meter_credit_balances` was the only copy, and nothing could
  # tell a clamp from a bug.
  @spec up() :: :ok
  def up do
    alter table(:aurora_meter_credit_transactions) do
      add_if_not_exists :promotional_after, :bigint
    end

    :ok
  end

  @spec down() :: :ok
  def down do
    alter table(:aurora_meter_credit_transactions) do
      remove_if_exists :promotional_after, :bigint
    end

    :ok
  end
end

defmodule AuroraMeter.Migration.V3 do
  @moduledoc false

  import Ecto.Migration

  # ADR: amounts are signed bigints in micro-dollars (1e-6 USD) so the ledger can
  # carry per-token AI prices (fractions of a cent) without floats or Decimal on
  # the hot path; `AuroraMeter.Credits.Money` converts at the edges. The
  # transactions table is append-only and every row snapshots `balance_after`
  # / `held_after`, so the balance can be audited or rebuilt from the log.
  @spec up() :: :ok
  def up do
    create_if_not_exists table(:aurora_meter_credit_balances, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :balance, :bigint, null: false, default: 0
      add :held, :bigint, null: false, default: 0
      add :promotional, :bigint, null: false, default: 0
      add :low_balance_threshold, :bigint
      add :currency, :string, null: false, default: "usd"
      timestamps(type: :utc_datetime_usec)
    end

    create_if_not_exists unique_index(:aurora_meter_credit_balances, [:tenant_key])

    create_if_not_exists table(:aurora_meter_credit_transactions, primary_key: false) do
      add :id, :binary_id, primary_key: true, default: fragment("gen_random_uuid()")
      add :tenant_key, :string, null: false
      add :kind, :string, null: false
      add :category, :string
      add :amount, :bigint, null: false
      add :held_delta, :bigint, null: false, default: 0
      add :balance_after, :bigint, null: false
      add :held_after, :bigint, null: false
      add :reference, :string
      add :status, :string
      add :settled_amount, :bigint
      add :expires_at, :utc_datetime
      add :expired_at, :utc_datetime
      add :metadata, :map, null: false, default: fragment("'{}'::jsonb")
      add :inserted_at, :utc_datetime_usec, null: false
    end

    # One grant / hold / debit per reference: the idempotency key for retries.
    create_if_not_exists unique_index(
                           :aurora_meter_credit_transactions,
                           [:kind, :reference],
                           where: "reference IS NOT NULL",
                           name: :aurora_meter_credit_transactions_kind_reference_index
                         )

    create_if_not_exists index(:aurora_meter_credit_transactions, [:tenant_key, :inserted_at])

    # Promotional grants still waiting to expire — what `Credits.expire_due/1` scans.
    create_if_not_exists index(
                           :aurora_meter_credit_transactions,
                           [:expires_at],
                           where:
                             "kind = 'grant' AND category = 'promotional' AND expired_at IS NULL",
                           name: :aurora_meter_credit_transactions_promo_expiry_index
                         )

    :ok
  end

  @spec down() :: :ok
  def down do
    drop_if_exists table(:aurora_meter_credit_transactions)
    drop_if_exists table(:aurora_meter_credit_balances)
    :ok
  end
end
