defmodule AuroraMeter.Exporter.Journal do
  @moduledoc """
  The reference `AuroraMeter.Exporter`: it records what it was handed and
  returns the answer it was told to.

  It exists for three jobs.

  **Teaching.** It is the whole of an exporter with the provider taken out, so
  the shape of one is readable in a few dozen lines rather than inferred from an
  SDK wrapper.

  **Testing.** A test scripts an answer for a subject reference and then asserts
  what the caller did with it. Scripting a rate limit or a lost acknowledgement
  is a line of code rather than a mocked HTTP layer.

  **A dry run.** A host that wants to see what *would* be exported, without
  exporting it, can configure this as its exporter and read `deliveries/1`. That
  is a legitimate production use, and the one thing to know before choosing it
  is in the next paragraph.

  ## It is memory, not a ledger

  The journal is an `Agent`. Its log lives in that process and is gone when the
  process stops, when the node restarts, or when anybody calls `reset/1`. It
  writes no file and no row. Do not use it as a record of what was billed.

  It is an `Agent` rather than the process dictionary on purpose: an answer
  scripted by a test process has to be visible to the worker process that calls
  `c:AuroraMeter.Exporter.deliver/2`, which is usually an Oban job or a `Task`,
  and a process-dictionary fake is invisible there. That defect exists in code
  this package's programme is replacing, and it is the reason two fakes could
  not be driven from the tests that needed them.

  ## Using it

      {:ok, _pid} = AuroraMeter.Exporter.Journal.start_link([])

      AuroraMeter.Exporter.Journal.script("usage:ai:2026-09-01:0:12", [{:retry, 30}, :accepted])

      AuroraMeter.Exporter.Journal.deliver([item], %{})
      #=> [{"row-1", {:retry, 30}}]
      AuroraMeter.Exporter.Journal.deliver([item], %{})
      #=> [{"row-1", :accepted}]

      AuroraMeter.Exporter.Journal.deliveries_for("usage:ai:2026-09-01:0:12")
      #=> [%{item: %AuroraMeter.Exporter.Item{}, outcome: {:retry, 30}, attempt: 0, at: ~U[...]}, ...]

  Scripted answers are consumed in order and then the default takes over, so
  "fail twice then succeed" is one call.

  ## It is deterministic

  No randomness, no sleeping, no message back to the caller. It records; it does
  not signal. A test that needs to observe a delivery while it is happening
  attaches its own `:telemetry` handler to the caller's event rather than asking
  the journal to tell it.

  The one exception is `{:raise, message}`, which is not an outcome and is the
  only way to script a provider call that blows up. It is here because
  `AuroraMeter.ExporterCase` has to prove that a caller survives one, and a
  conformance area that no adapter can reach is a conformance area that proves
  nothing. A journal that has not been scripted with it never raises.

  ## What it is scripted with

  `script/2` takes **any term**, not only the five documented outcomes. That is
  deliberate: the point of the malformed-response and unknown-status areas of
  `AuroraMeter.ExporterCase` is that a provider can say something nobody
  planned for, and `AuroraMeter.Exporter.normalize/2` has to reduce it to
  `:uncertain`. An adapter that could only return valid outcomes could not
  exercise that path.
  """

  alias AuroraMeter.Clock
  alias AuroraMeter.Exporter
  alias AuroraMeter.Exporter.Item

  @behaviour AuroraMeter.Exporter

  @default_description %{
    max_batch: 100,
    idempotency_horizon: 86_400,
    timestamp_window: %{past: 2_592_000, future: 300},
    supports: [:usage_window, :event, :correction]
  }

  @typedoc "One recorded delivery, in the order the journal saw it."
  @type entry :: %{
          item: Item.t(),
          outcome: term(),
          attempt: non_neg_integer(),
          at: DateTime.t()
        }

  @doc """
  Starts the journal.

  Options: `:name` (default `AuroraMeter.Exporter.Journal`), `:describe` (a
  `t:AuroraMeter.Exporter.description/0`, defaulting to
  `#{inspect(@default_description)}`) and `:default_outcome` (the answer for a
  subject reference nothing was scripted for, default `:accepted`).
  """
  @spec start_link(keyword()) :: Agent.on_start()
  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)

    state = %{
      describe: Keyword.get(opts, :describe, @default_description),
      default: Keyword.get(opts, :default_outcome, :accepted),
      scripted: %{},
      log: []
    }

    Agent.start_link(fn -> state end, name: name)
  end

  @doc """
  The child specification, so a host can start the journal from its own
  supervision tree.

  Written out rather than generated by `use Agent`, because the id is the
  journal's name: a host that runs a second journal under another name must be
  able to start both.
  """
  @spec child_spec(keyword()) :: Supervisor.child_spec()
  def child_spec(opts) do
    %{id: Keyword.get(opts, :name, __MODULE__), start: {__MODULE__, :start_link, [opts]}}
  end

  @doc "The description this journal was started with, or the default when it is not running."
  @impl AuroraMeter.Exporter
  @spec describe() :: Exporter.description()
  def describe do
    case Process.whereis(__MODULE__) do
      nil -> @default_description
      pid -> Agent.get(pid, & &1.describe)
    end
  end

  @doc "The description a journal falls back to when it was started with none."
  @spec default_description() :: Exporter.description()
  def default_description, do: @default_description

  @doc """
  Records every item and answers each one.

  The answer for an item is the next scripted entry for its `subject_ref`, or
  the journal's default outcome when the queue for that reference is empty.
  Entries come back in the caller's input order.

  Exits with `:noproc` when the journal is not running: an exporter that cannot
  reach its provider must not quietly report success, and the caller's rescue
  turns the exit into `:uncertain`, which is the truthful answer.
  """
  @impl AuroraMeter.Exporter
  @spec deliver([Item.t()], Exporter.context()) :: [Exporter.result()]
  def deliver(items, context) when is_list(items) and is_map(context) do
    at = Clock.now()

    {results, raise_messages} =
      Agent.get_and_update(__MODULE__, fn state ->
        {entries, state} = Enum.map_reduce(items, state, &record(&1, &2, at))

        results = for %{item: item, outcome: outcome} <- entries, do: {item.id, outcome}

        raise_messages =
          for %{outcome: {:raise, message}} <- entries, do: message

        {{results, raise_messages}, state}
      end)

    case raise_messages do
      [] -> results
      [message | _rest] -> raise RuntimeError, message
    end
  end

  @doc """
  Queues one outcome, or a list of them, for `subject_ref`.

  Any term is accepted. A list is consumed one delivery at a time, in order, and
  the journal falls back to its default outcome once the queue is empty.
  """
  @spec script(String.t(), term() | [term()]) :: :ok
  def script(subject_ref, outcomes), do: script(__MODULE__, subject_ref, outcomes)

  @doc "As `script/2`, against a journal started under `name`."
  @spec script(Agent.agent(), String.t(), term() | [term()]) :: :ok
  def script(name, subject_ref, outcomes) when is_binary(subject_ref) do
    queued = if is_list(outcomes), do: outcomes, else: [outcomes]

    Agent.update(name, fn state ->
      update_in(state.scripted, &Map.update(&1, subject_ref, queued, fn old -> old ++ queued end))
    end)
  end

  @doc "Every delivery this journal recorded, oldest first."
  @spec deliveries() :: [entry()]
  def deliveries, do: deliveries(__MODULE__)

  @doc "As `deliveries/0`, against a journal started under `name`."
  @spec deliveries(Agent.agent()) :: [entry()]
  def deliveries(name), do: Agent.get(name, &Enum.reverse(&1.log))

  @doc "The deliveries recorded for one subject reference, oldest first."
  @spec deliveries_for(String.t()) :: [entry()]
  def deliveries_for(subject_ref), do: deliveries_for(__MODULE__, subject_ref)

  @doc "As `deliveries_for/1`, against a journal started under `name`."
  @spec deliveries_for(Agent.agent(), String.t()) :: [entry()]
  def deliveries_for(name, subject_ref) do
    Enum.filter(deliveries(name), &(&1.item.subject_ref == subject_ref))
  end

  @doc "Empties the log and the scripted queues, keeping the description and the default."
  @spec reset() :: :ok
  def reset, do: reset(__MODULE__)

  @doc "As `reset/0`, against a journal started under `name`."
  @spec reset(Agent.agent()) :: :ok
  def reset(name), do: Agent.update(name, &%{&1 | scripted: %{}, log: []})

  # -- internals --------------------------------------------------------------

  defp record(%Item{} = item, state, at) do
    {outcome, scripted} = take(state.scripted, item.subject_ref, state.default)
    entry = %{item: item, outcome: outcome, attempt: item.attempts, at: at}

    {entry, %{state | scripted: scripted, log: [entry | state.log]}}
  end

  defp take(scripted, subject_ref, default) do
    case Map.get(scripted, subject_ref) do
      nil -> {default, scripted}
      [] -> {default, scripted}
      [next | rest] -> {next, Map.put(scripted, subject_ref, rest)}
    end
  end
end
