import Config

# Configure your database
config :aurora_meter_example_ai, AuroraMeterExampleAi.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("DB_HOST") || "localhost",
  # 5490 is the port the Aurora Meter package's own Postgres container listens
  # on, so the sample needs no second database server. Nothing else about the
  # sample depends on it: set DB_PORT for your own.
  port: String.to_integer(System.get_env("DB_PORT") || "5490"),
  # `DB_NAME` so a run can point the sample at a disposable database of its
  # own. `scripts/pro-proof.sh` uses it: a proof that creates real Stripe
  # objects must not also write into the database you have been reading all
  # morning.
  database: System.get_env("DB_NAME") || "aurora_meter_example_ai_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :aurora_meter_example_ai, AuroraMeterExampleAiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LE3M7pOdNemF6rkrUJ0g5/pH16/f9kMAkvPkmRtGwMlU53WpOLMZGfLeJMLW45H7",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:aurora_meter_example_ai, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:aurora_meter_example_ai, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :aurora_meter_example_ai, dev_routes: true

# The sample's own development switches.
config :aurora_meter_example_ai,
  # `/dev/tools`, which mints synthetic credit. Off everywhere else.
  dev_tools: true,
  # A visible pause per completion token, in microseconds, so a human clicking
  # "generate" watches the meter move rather than finding it already moved.
  # Zero in test.
  workload_micros_per_token: 1_500,
  # How often the outbox drainer ticks.
  outbox_interval: 1_000

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
