defmodule AuroraMeter.ApiInventoryTest do
  @moduledoc """
  Guards the published API inventory in `docs/api.md`.

  Five unit-local invariants, named in build unit 02a:

    * A01: every `Module.function/arity` listed in `docs/api.md` exists at
      runtime, except rows tagged `optional-dep` whose module is absent.
    * A02: nothing internal (`@doc false`, or a module in `@internal_modules`)
      appears in `docs/api.md`.
    * A03: every non-internal module under `lib/` carries a real `@moduledoc`.
    * A04: every public function of a non-internal module carries a `@spec`,
      unless it is listed in `@spec_exceptions` with a reason.
    * A05: every telemetry event and PubSub tag documented in `docs/api.md`
      appears verbatim in `lib/`.

  The test reflects on compiled modules and reads `docs/api.md` as text. It
  touches no database and starts nothing, so it is `async: true`.

  `docs/api.md` is parsed by the HTML comments `<!-- inventory:<mode> -->`.
  Everything before the first one, and everything in an `inventory:none`
  region, is prose. Inside a region, the first row of each table is its header
  and every later row must carry a single inline-code span in its first cell.
  """
  use ExUnit.Case, async: true

  alias AuroraMeter.Test.TelemetryCensus

  @inventory "docs/api.md"

  # The internal set fixed by `api-change-map.md` section 1.8 and section 6.2,
  # restricted to modules that exist in this release. It is the single source of
  # truth for A02, A03 and A04, it is the "Internal modules" section of
  # `docs/api.md`, and `mix.exs`'s "Internal" module group must equal it.
  @internal_modules [
    AuroraMeter.BootChecks,
    AuroraMeter.Bench.DelayStorage,
    AuroraMeter.Bench.MemoryStorage,
    AuroraMeter.Bench.Mode,
    AuroraMeter.Bench.Modes,
    AuroraMeter.Bench.Modes.Cluster,
    AuroraMeter.Bench.Modes.Counters,
    AuroraMeter.Bench.Modes.Durable,
    AuroraMeter.Bench.Modes.Faults,
    AuroraMeter.Bench.Modes.Flush,
    AuroraMeter.Bench.Modes.Quota,
    AuroraMeter.Bench.Modes.Wallet,
    AuroraMeter.Bench.Plans,
    AuroraMeter.Bench.Report,
    AuroraMeter.Bench.Runner,
    AuroraMeter.Bench.Stats,
    AuroraMeter.Broadcaster,
    AuroraMeter.Cluster,
    AuroraMeter.Config.Schema,
    AuroraMeter.Counter,
    AuroraMeter.Credits.Allocator,
    AuroraMeter.Credits.Ledger,
    AuroraMeter.Credits.Promotions,
    AuroraMeter.Credits.Reconciliation,
    AuroraMeter.Credits.Series,
    AuroraMeter.Events.Backfill,
    AuroraMeter.Events.Canonical,
    AuroraMeter.Events.Gate,
    AuroraMeter.Install.Options,
    AuroraMeter.Install.Plan,
    AuroraMeter.Install.Shell,
    AuroraMeter.Install.Templates,
    AuroraMeter.LiveDashboard.Auth,
    AuroraMeter.LiveDashboard.NotStartedError,
    AuroraMeter.LiveDashboard.Sections,
    AuroraMeter.LiveDashboard.View,
    AuroraMeter.Migration.V1,
    AuroraMeter.Migration.V2,
    AuroraMeter.Migration.V3,
    AuroraMeter.Migration.V4,
    AuroraMeter.Migration.V5,
    AuroraMeter.Migration.V6,
    AuroraMeter.Migration.V7,
    AuroraMeter.Migration.V8,
    AuroraMeter.Migration.V9,
    AuroraMeter.Migration.V10,
    AuroraMeter.OpenTelemetry.Bridge,
    AuroraMeter.OpenTelemetry.Tracer,
    AuroraMeter.Plans.Snapshot,
    AuroraMeter.Schema.FlushReceipt,
    AuroraMeter.Storage.Ecto,
    AuroraMeter.Store,
    AuroraMeter.Subscriptions.Preview,
    AuroraMeter.Subscriptions.Transitions,
    AuroraMeter.Supervisor
  ]

  # The one entry of an internal module that `docs/api.md` is allowed to list,
  # because a host has to build the topic string to subscribe to it.
  # `api-change-map.md` 1.8: "keep `topic/1` documented".
  @internal_carve_outs [{AuroraMeter.Broadcaster, :topic, 1}]

  # Functions of internal modules that must keep a real `@doc` even though the
  # module is internal, because a host or the test helpers still call them.
  @must_stay_documented [
    {AuroraMeter.Flusher, :flush, 0},
    {AuroraMeter.Broadcaster, :topic, 1},
    {AuroraMeter.Subscriptions, :get, 1},
    {AuroraMeter.Subscriptions, :invalidate, 1},
    {AuroraMeter.Cluster, :apply, 3}
  ]

  # `{module, function, arity, reason}`. A04 fails when an entry carries no
  # reason and when an entry is no longer needed, so the list cannot rot.
  @spec_exceptions [
    {AuroraMeter.Clock.Fixed, :child_spec, 1,
     "generated by `use Agent`; the contract is OTP's `Supervisor.child_spec/0` " <>
       "and a hand-written spec here would restate it at the risk of drifting from it"},
    {AuroraMeter.Flusher, :child_spec, 1,
     "generated by `use GenServer`; same reason as `AuroraMeter.Clock.Fixed.child_spec/1`"},
    {AuroraMeter.Components, :usage_meter, 1,
     "HEEx function component: the typed contract is its `attr/3` declarations, which " <>
       "ExDoc renders, and its return type belongs to an optional dependency"},
    {AuroraMeter.Components, :usage_summary, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.Components, :spend_chart, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.Components, :credit_summary, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.LiveDashboard.Page, :render, 1,
     "HEEx: the typed contract is `Phoenix.LiveDashboard.PageBuilder`'s `render/1` callback, " <>
       "and its return type belongs to an optional dependency"},
    {AuroraMeter.Plans, :plan, 2,
     "plans DSL macro: it is usable only inside a module that `use`s `AuroraMeter.Plans`, " <>
       "and a spec would describe the AST it receives rather than the DSL it accepts"},
    {AuroraMeter.Plans, :plan, 3,
     "plans DSL macro: `plan :pro, version: \"2\" do ... end` parses as three arguments, " <>
       "the id, the options and the do block, so the versioned form is arity 3"},
    {AuroraMeter.Plans, :price, 1, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :limit, 3, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :metered, 2, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :feature, 2, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :counter, 1, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :recurring_credits, 2, "plans DSL macro, as `plan/2`"}
  ]

  setup_all do
    %{regions: parse_inventory(@inventory)}
  end

  describe "A01 the inventory resolves" do
    test "every function listed in docs/api.md exists", %{regions: regions} do
      # The skip condition asks about the row's own DEPENDENCY, not about its
      # module. Those were the same question while every optional integration
      # was a whole module behind a guard (`Components`, `Oban.*`,
      # `LiveDashboard.Page`, `OpenTelemetry`, `Telemetry.Metrics`). Build unit
      # 09a's `AuroraMeter.LiveView` is the first module that is ALWAYS compiled
      # and puts only four of its functions behind `Code.ensure_loaded?`, so on
      # a build without LiveView the module is present and the functions are
      # not, and `module_present?/1` said "require them" for exactly the rows
      # that are correctly absent. Found by the `plug_only` leg.
      missing =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            not skip_absent_optional?(row),
            not exported?(module, fun, arity),
            do: {row.line, format_entry(entry)}

      assert missing == [], "docs/api.md names functions that do not exist:\n" <> lines(missing)
    end

    test "every module listed in docs/api.md exists", %{regions: regions} do
      # `skip_absent_dependency?/1` rather than `optional_dep?/1` here, because
      # the **internal** table has two columns and no Class cell, so a row in it
      # can never carry the `optional-dep` tag. `AuroraMeter.LiveDashboard.View`
      # is internal AND compiled behind `Code.ensure_loaded?(Phoenix.Component)`,
      # so this test had been failing on the headless leg since 08b landed the
      # row, and only the legs run it (`open-findings.md` X246's shape exactly:
      # the leg is not part of `mix check`, so nothing else says so). Found by
      # build unit 09a's headless run.
      missing =
        for row <- rows(regions, :modules) ++ rows(regions, :internal),
            module = module_entry!(row),
            not skip_absent_dependency?(row),
            not module_present?(module),
            do: {row.line, inspect(module)}

      assert missing == [], "docs/api.md names modules that do not exist:\n" <> lines(missing)
    end

    test "every optional-dependency row names the dependency it needs",
         %{regions: regions} do
      optional = Enum.filter(rows(regions, :functions), &optional_dep?/1)

      assert optional != [],
             "no row in docs/api.md is tagged optional-dep, so the tag has rotted away"

      unnamed =
        for row <- optional, needed_dependency(row) == nil, do: {row.line, literal_of(row)}

      assert unnamed == [],
             "these rows are tagged optional-dep and do not say which dependency they need, " <>
               "so nothing can check when they are allowed to be absent:
" <> lines(unnamed)
    end

    test "each optional-dependency row is present exactly when ITS OWN dependency is",
         %{regions: regions} do
      # Not "when Phoenix.Component is loaded". That is what this assertion used
      # to say, and it was true only while every optional row needed LiveView or
      # Oban and one environment variable removed both together. The moment a
      # second, independently removable optional dependency arrived
      # (`telemetry_metrics`), the test became wrong in whichever direction the
      # build happened to be: on a leg that removes only the metrics reporter it
      # fails, because Phoenix.Component is loaded and two rows are correctly
      # skipped (`open-findings.md` X326).
      # And for the same reason, the presence probe is the FUNCTION rather than
      # its module: `AuroraMeter.LiveView` is compiled on every build and only
      # four of its functions are guarded, so asking `module_present?/1` about
      # them answers a question nobody asked.
      wrong =
        for row <- Enum.filter(rows(regions, :functions), &optional_dep?/1),
            dependency = needed_dependency(row),
            dependency != nil,
            {module, fun, arity} = function_entry!(row),
            exported?(module, fun, arity) != dependency_present?(dependency),
            do:
              {row.line,
               "#{literal_of(row)} needs #{dependency}: dependency loaded?=" <>
                 "#{dependency_present?(dependency)} function exported?=" <>
                 "#{exported?(module, fun, arity)}"}

      assert wrong == [],
             "an optional-dep row is present when its dependency is absent, or absent when " <>
               "its dependency is present:
" <> lines(wrong)
    end

    test "every documented configuration key is in the schema", %{regions: regions} do
      known = Keyword.keys(AuroraMeter.Config.schema().schema)

      documented =
        for row <- rows(regions, :config) do
          row |> first_code_span!() |> String.trim_leading(":") |> String.to_atom()
        end

      assert documented != [], "docs/api.md documents no configuration key"
      assert documented -- known == [], "documented keys that the schema does not declare"
      assert known -- documented == [], "schema keys that docs/api.md does not document"
    end
  end

  describe "A02 the inventory excludes what is internal" do
    test "no module marked internal appears in the inventory", %{regions: regions} do
      offenders =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            module in @internal_modules,
            {module, fun, arity} not in @internal_carve_outs,
            do: {row.line, format_entry(entry)}

      module_rows =
        for row <- rows(regions, :modules),
            module = module_entry!(row),
            module in @internal_modules,
            # A module row may name an internal module as long as it says so.
            not String.contains?(row.raw, "internal"),
            do: {row.line, inspect(module)}

      assert offenders ++ module_rows == [],
             "internal entries listed as supported API:\n" <> lines(offenders ++ module_rows)
    end

    test "no @doc false function appears in the inventory", %{regions: regions} do
      offenders =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            module_present?(module),
            hidden?(module, fun, arity),
            do: {row.line, format_entry(entry)}

      assert offenders == [],
             "docs/api.md lists functions carrying @doc false:\n" <> lines(offenders)
    end

    test "the internal section and @internal_modules are the same list", %{regions: regions} do
      documented = regions |> rows(:internal) |> Enum.map(&module_entry!/1) |> Enum.sort()

      assert documented == Enum.sort(@internal_modules),
             "the \"Internal modules\" section of docs/api.md and @internal_modules disagree"
    end

    test "mix.exs puts exactly @internal_modules in the Internal docs group" do
      groups = Mix.Project.config()[:docs][:groups_for_modules] || []
      internal = groups |> Keyword.get(:Internal, []) |> Enum.sort()

      assert internal == Enum.sort(@internal_modules),
             "mix.exs groups_for_modules[:Internal] and @internal_modules disagree"
    end

    test "internal modules keep the entries a host still calls documented" do
      undocumented =
        for {module, fun, arity} <- @must_stay_documented,
            doc_for(module, fun, arity) in [:none, :hidden],
            do: {0, "#{inspect(module)}.#{fun}/#{arity}"}

      assert undocumented == [],
             "these must keep a real @doc:\n" <> lines(undocumented)
    end

    test "every internal module carries the stability banner" do
      banner = "**Internal.**"

      missing =
        for module <- @internal_modules,
            %{} = doc <- [moduledoc(module)],
            not String.contains?(Map.get(doc, "en", ""), banner),
            do: {0, inspect(module)}

      assert missing == [],
             "internal modules whose @moduledoc lacks the stability banner:\n" <> lines(missing)
    end
  end

  describe "A03 moduledocs" do
    test "every non-internal module under lib/ has a moduledoc" do
      missing =
        for module <- lib_modules(),
            module not in @internal_modules,
            moduledoc(module) in [:none, :hidden],
            do: {0, "#{inspect(module)} (#{inspect(moduledoc(module))})"}

      assert missing == [], "modules without a @moduledoc:\n" <> lines(missing)
    end
  end

  describe "A04 specs" do
    test "every public function of a non-internal module has a spec" do
      missing =
        for module <- lib_modules(),
            module not in @internal_modules,
            entry <- public_entries(module),
            not spec?(module, entry),
            not excepted?(module, entry),
            do: {0, describe_entry(module, entry)}

      assert missing == [], "public functions without a @spec:\n" <> lines(missing)
    end

    test "every spec exception carries a reason" do
      for {module, fun, arity, reason} <- @spec_exceptions do
        assert is_binary(reason) and String.trim(reason) != "",
               "#{inspect(module)}.#{fun}/#{arity} is spec-excepted with no reason"
      end
    end

    test "no spec exception is stale" do
      stale =
        for {module, fun, arity, _reason} <- @spec_exceptions,
            module_present?(module),
            spec?(module, {:function, fun, arity}) or
              spec?(module, {:macro, fun, arity}) or
              ({:function, fun, arity} not in public_entries(module) and
                 {:macro, fun, arity} not in public_entries(module)),
            do: {0, "#{inspect(module)}.#{fun}/#{arity}"}

      assert stale == [], "spec exceptions that are no longer needed:\n" <> lines(stale)
    end
  end

  describe "A06 the documented signature is the real one" do
    # `open-findings.md` X370 and X229. A01 asks whether a documented function
    # EXISTS, which is a different question from whether the type printed beside
    # it is the type it has. `AuroraMeter.Pro.Reconcile.run/1` carried
    # `(keyword()) :: [map()]` for a whole release after 04d changed it, and
    # `Credits.hold/4`, `debit/4` and `with_credits/4` printed a two-atom error
    # union for as long as it took somebody to notice `:debt_outstanding` was
    # missing. Nothing failed either time, because nothing compared the two.
    # Until something does, the inventory is a list of names rather than of
    # contracts, and should be read as one.
    #
    # `Code.Typespec.fetch_specs/1` gives the real spec at run time, so the
    # comparison is cheap. It is not exact, and deliberately so: the inventory
    # abbreviates (`tenant` for `AuroraMeter.tenant()`, `map()` where the spec
    # names a struct type), which is a readability decision rather than a
    # defect. Two things are exact, and both are what a caller writes code
    # against:
    #
    #   * the number of arguments, against the arity in the entry;
    #   * the **match surface** of the return, in both directions: the atom
    #     members of the top-level union, the leading atom of each top-level
    #     tuple, and the tag one level inside it. An error tag the spec can
    #     return and the table does not print is a `case` clause a reader will
    #     not write, which is X370 exactly; an atom the table prints and the
    #     spec cannot produce is a promise the code does not keep.
    #
    # Argument types are not compared beyond their count, because `keyword()`
    # against `[{:rounding, :round | :floor | :ceil}]` is the abbreviation
    # working as intended, and a check that failed it would be noise somebody
    # switches off.
    test "every documented argument count matches the entry's arity", %{regions: regions} do
      wrong =
        for row <- rows(regions, :functions),
            {module, fun, arity} = function_entry!(row),
            not skip_absent_optional?(row),
            documented = documented_arity(row),
            documented != nil,
            documented != arity,
            do:
              {row.line,
               "#{format_entry({module, fun, arity})}: the signature cell shows " <>
                 "#{documented} arguments"}

      assert wrong == [],
             "docs/api.md prints a signature whose argument count is not the entry's " <>
               "arity:\n" <> lines(wrong)
    end

    test "every documented return prints the atoms the @spec can return", %{regions: regions} do
      wrong =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            not skip_absent_optional?(row),
            returns = spec_returns(module, fun, arity),
            returns != nil,
            documented = signature_cell(row),
            documented != nil,
            {missing, extra} <- [atom_difference(documented, returns, module)],
            missing != [] or extra != [],
            do:
              {row.line,
               "#{format_entry(entry)}\n" <>
                 "      documented: #{documented}\n" <>
                 "      @spec     : #{Enum.join(returns, " and ")}\n" <>
                 "      the spec can return and the table does not print: #{inspect(missing)}\n" <>
                 "      the table prints and the spec cannot return: #{inspect(extra)}"}

      assert wrong == [],
             "docs/api.md prints a return type whose match surface is not the one the " <>
               "@spec declares. The page ships to hexdocs, so the type a reader sees is " <>
               "the one they write their `case` against:\n" <> lines(wrong)
    end

    test "the comparison examined the rows it was meant to examine", %{regions: regions} do
      # A guard that compared nothing would pass for ever (X324, X325). Count
      # the rows that actually reached the comparison, not the rows that exist,
      # and count the ones it could not parse so an opt-out cannot grow quietly.
      outcomes =
        for row <- rows(regions, :functions),
            {module, fun, arity} = function_entry!(row),
            not skip_absent_optional?(row),
            returns = spec_returns(module, fun, arity),
            returns != nil,
            documented = signature_cell(row),
            documented != nil,
            do: atom_difference(documented, returns, module)

      compared = Enum.count(outcomes, &(&1 != :unparsable))
      unparsable = Enum.count(outcomes, &(&1 == :unparsable))

      assert compared >= 150,
             "only #{compared} inventory rows reached the signature comparison. A shrunken " <>
               "selection is a failure, not a pass."

      assert unparsable <= 5,
             "#{unparsable} rows could not be parsed as a type expression and were skipped. " <>
               "Each one is a row this check is not looking at."
    end

    test "the comparison reports a return type that disagrees with its spec" do
      # The permanent negative control. Without it, "no disagreements" is
      # satisfied both by a correct page and by a comparison that answers the
      # same thing about every input.
      assert atom_difference("(tenant) :: :ok | {:error, :nope}", "f(term()) :: :ok") ==
               {[], [:error, :nope]}

      # X370's own shape: the spec gained an error tag and the table did not.
      assert atom_difference(
               "(tenant) :: {:ok, txn()} | {:error, :insufficient_credits}",
               "hold(term()) :: {:ok, txn()} | {:error, :insufficient_credits | :debt_outstanding}"
             ) == {[:debt_outstanding], []}

      # A nested tag is part of the match surface.
      assert atom_difference(
               "(map()) :: {:ok, t()} | {:error, term()}",
               "put(map()) :: {:ok, t()} | {:error, term()} | {:error, {:unsupported, cap()}}"
             ) == {[:unsupported], []}

      # And it must stay quiet where the table abbreviates on purpose, or it
      # reports every row and gets switched off.
      assert atom_difference("(tenant) :: {:ok, map()}", "f(term()) :: {:ok, report()}") ==
               {[], []}

      assert atom_difference(
               "(tenant, keyword()) :: [{:usage | :credits, String.t()}]",
               "topics(term(), keyword()) :: [{topic_name(), String.t()}]"
             ) == {[], []}

      # A named type met at a match position is resolved, so the side that
      # writes `error()` and the side that writes the union out agree.
      assert atom_difference(
               "(tenant) :: {:ok, map()} | " <>
                 "{:error, {:invalid | :conflict | :not_found | :unavailable, term()}}",
               "f(term()) :: {:ok, map()} | {:error, error()}",
               AuroraMeter.Subscriptions
             ) == {[], []}

      assert documented_arity(%{cells: ["`x`", "`(a, b) :: :ok`"]}) == 2
      assert documented_arity(%{cells: ["`x`", "`() :: :ok`"]}) == 0
      assert documented_arity(%{cells: ["`x`", "prose"]}) == nil
    end
  end

  describe "A07 every worked example is run" do
    # `open-findings.md` X237. `AuroraMeter.Pro.Export.daily_csv/3` carried an
    # `iex>` example that no `doctest` declaration anywhere referenced, so it
    # was prose shaped like a proof. Adding the one declaration fixes one
    # module and leaves the next one exactly as invisible; this asks the general
    # question, which is the one worth having.
    test "every module with an iex> example is named by a doctest declaration" do
      declared = doctested_modules()

      undoctested =
        for module <- lib_modules(),
            has_iex_example?(module),
            module not in declared,
            do: {0, inspect(module)}

      assert undoctested == [],
             "these modules carry an `iex>` example that nothing runs, so it is prose " <>
               "shaped like a proof. Add a `doctest` declaration for each to a test file, " <>
               "or write the example as a fenced block rather than an `iex>` prompt:\n" <>
               lines(undoctested)
    end

    test "the doctest scan found declarations and examples at all" do
      assert MapSet.size(doctested_modules()) >= 3,
             "no doctest declarations were found, so the check above cannot fail"

      assert Enum.count(lib_modules(), &has_iex_example?/1) >= 3,
             "no module was found carrying an `iex>` example, so the check above is asking " <>
               "nothing of anything"
    end

    test "a doctested module really does carry the example it is declared for" do
      # Both halves of the check have to be non-empty on today's tree or the
      # assertion above passes vacuously.
      subject = doctested_modules() |> Enum.find(&has_iex_example?/1)

      assert subject != nil,
             "no doctested module carries an `iex>` example, so this control proves nothing"

      refute has_iex_example?(AuroraMeter.Supervisor) and
               AuroraMeter.Supervisor not in doctested_modules(),
             "the scan disagrees with itself"
    end
  end

  describe "A05 documented literals exist in lib/" do
    # Doc strings and comments are stripped first. Mentioning an event in a
    # moduledoc is not emitting it, and a check that accepted the mention would
    # pass for an event that had been renamed at the only place that matters.
    test "every telemetry event and PubSub tag appears verbatim in lib/ code",
         %{regions: regions} do
      sites = telemetry_sites()
      code = lib_code()

      missing =
        for row <- rows(regions, :literal),
            literal = literal!(row),
            not present?(literal, sites, code),
            do: {row.line, literal}

      assert missing == [],
             "documented in docs/api.md but not emitted anywhere in lib/:\n" <> lines(missing)
    end

    test "the literal sections name at least the events and messages that exist",
         %{regions: regions} do
      literals = regions |> rows(:literal) |> Enum.map(&literal!/1)

      pubsub = Enum.count(literals, &String.starts_with?(&1, "{:aurora_meter"))

      # Distinct names, in both directions, rather than a count of emit sites.
      # A count is satisfied by any two numbers that happen to agree, and it
      # broke the moment one event acquired a second emit site: the flush span
      # and the flat flush event share a name, which is two sites and one
      # contract.
      documented =
        literals |> Enum.filter(&String.starts_with?(&1, "[:aurora_meter")) |> MapSet.new()

      emitted = MapSet.new(telemetry_sites())

      assert MapSet.difference(emitted, documented) |> MapSet.to_list() == [],
             "lib/ emits telemetry events docs/api.md does not list"

      assert MapSet.difference(documented, emitted) |> MapSet.to_list() == [],
             "docs/api.md lists telemetry events lib/ does not emit"

      assert pubsub >= 6, "docs/api.md documents only #{pubsub} PubSub messages"
    end
  end

  # The dependency an optional-dep row names in its Notes ("Needs `oban`"). The
  # row has to say, because a tag that means "optional somehow" cannot be
  # checked against anything.
  defp needed_dependency(row) do
    case Regex.run(~r/Needs `([a-z_0-9]+)`/, row.raw) do
      [_, name] -> name
      nil -> nil
    end
  end

  # One probe module per dependency this package declares as optional. A
  # dependency that arrives without an entry here fails the test above rather
  # than being silently treated as present.
  defp dependency_present?("oban"), do: Code.ensure_loaded?(Oban)
  defp dependency_present?("phoenix_live_view"), do: Code.ensure_loaded?(Phoenix.LiveView)
  defp dependency_present?("phoenix_html"), do: Code.ensure_loaded?(Phoenix.HTML)
  defp dependency_present?("igniter"), do: Code.ensure_loaded?(Igniter)
  defp dependency_present?("telemetry_metrics"), do: Code.ensure_loaded?(Telemetry.Metrics)

  defp dependency_present?("phoenix_live_dashboard"),
    do: Code.ensure_loaded?(Phoenix.LiveDashboard.PageBuilder)

  defp dependency_present?("opentelemetry_api"), do: Code.ensure_loaded?(:otel_tracer)
  defp dependency_present?("plug"), do: Code.ensure_loaded?(Plug.Conn)

  defp dependency_present?(other) do
    flunk("docs/api.md names an optional dependency this test has no probe for: #{other}")
  end

  defp literal_of(row) do
    case Regex.run(~r/^\|\s*`([^`]+)`/, row.raw) do
      [_, text] -> text
      nil -> String.slice(row.raw, 0, 60)
    end
  end

  # -- inventory parsing -----------------------------------------------------

  defp parse_inventory(path) do
    path
    |> File.read!()
    |> String.split("\n")
    |> Enum.with_index(1)
    |> Enum.reduce({:none, :outside, [], []}, &parse_line/2)
    |> elem(2)
    |> Enum.reverse()
  end

  defp parse_line({line, number}, {mode, table, acc, header}) do
    cond do
      match = Regex.run(~r/^<!--\s*inventory:([a-z]+)\s*-->\s*$/, line) ->
        {String.to_atom(Enum.at(match, 1)), :outside, acc, []}

      not String.starts_with?(String.trim(line), "|") ->
        {mode, :outside, acc, header}

      table == :outside ->
        {mode, :header, acc, cells(line)}

      table == :header ->
        {mode, :body, acc, header}

      true ->
        row = %{mode: mode, line: number, raw: line, cells: cells(line), header: header}
        {mode, :body, [row | acc], header}
    end
  end

  defp cells(line) do
    line
    |> String.trim()
    |> String.trim_leading("|")
    |> String.trim_trailing("|")
    |> then(&Regex.split(~r/(?<!\\)\|/, &1))
    |> Enum.map(&String.trim/1)
  end

  defp rows(regions, mode), do: Enum.filter(regions, &(&1.mode == mode))

  defp first_code_span!(row) do
    cell = hd(row.cells)

    case Regex.run(~r/^`([^`]+)`$/, cell) do
      [_, text] ->
        text

      _ ->
        flunk(
          "docs/api.md line #{row.line}: the first cell of a row in an inventory section " <>
            "must be a single inline-code span, got #{inspect(cell)}"
        )
    end
  end

  defp function_entry!(row) do
    text = first_code_span!(row)

    case Regex.run(~r/^([A-Za-z0-9_.]+)\.([a-z_][A-Za-z0-9_?!]*)\/(\d+)$/, text) do
      [_, module, fun, arity] ->
        {Module.concat([module]), String.to_atom(fun), String.to_integer(arity)}

      _ ->
        flunk("docs/api.md line #{row.line}: expected `Module.function/arity`, got `#{text}`")
    end
  end

  defp module_entry!(row) do
    text = first_code_span!(row)

    unless Regex.match?(~r/^[A-Z][A-Za-z0-9_.]*$/, text) do
      flunk("docs/api.md line #{row.line}: expected a module name, got `#{text}`")
    end

    Module.concat([text])
  end

  @literal_column "Matched in lib/"

  # Literal rows carry the greppable source text in a column of their own, so
  # the human-readable event name in the first cell can differ from the source
  # (`[:aurora_meter, :credits, kind]` is emitted as `txn.kind`). The column is
  # found by its header text, never by its position (open-findings.md X67).
  defp literal!(row) do
    index =
      Enum.find_index(row.header, &(&1 == @literal_column)) ||
        flunk(
          "docs/api.md line #{row.line}: a literal table needs a #{inspect(@literal_column)} " <>
            "column, its header is #{inspect(row.header)}"
        )

    cell = Enum.at(row.cells, index, "")

    case Regex.run(~r/^`(.+)`$/, cell) do
      [_, text] ->
        String.replace(text, "\\|", "|")

      _ ->
        flunk(
          "docs/api.md line #{row.line}: the #{inspect(@literal_column)} cell must be a " <>
            "single inline-code span holding the source text, got #{inspect(cell)}"
        )
    end
  end

  defp optional_dep?(row), do: Enum.any?(row.cells, &(&1 == "optional-dep"))

  # Whether a row is allowed to be absent on THIS build: it is tagged
  # `optional-dep`, it names the dependency it needs, and that dependency is not
  # here. A row tagged `optional-dep` that names no dependency is not skipped;
  # the test above it fails such a row by name, so this cannot become a way to
  # excuse a row nothing can check.
  defp skip_absent_optional?(row) do
    optional_dep?(row) and skip_absent_dependency?(row)
  end

  # Whether the row names a dependency that is not in this build. The name has
  # to be one `dependency_present?/1` has a probe for, and that function
  # `flunk`s on a name it does not know, so this cannot become a way to excuse a
  # row by inventing a dependency.
  defp skip_absent_dependency?(row) do
    case needed_dependency(row) do
      dependency when is_binary(dependency) -> not dependency_present?(dependency)
      nil -> false
    end
  end

  # -- reflection ------------------------------------------------------------

  defp lib_root, do: Path.expand("lib") <> "/"

  defp lib_modules do
    {:ok, modules} = :application.get_key(:aurora_meter, :modules)

    modules
    |> Enum.filter(&from_lib?/1)
    |> Enum.sort()
  end

  defp lib_sources do
    "lib/**/*.ex" |> Path.wildcard() |> Enum.map(&File.read!/1)
  end

  # `lib/` with every heredoc (which is every `@moduledoc` and `@doc`, plus the
  # installer's templates) and every whole-line comment removed, so a literal
  # found here is one the code actually uses.
  defp lib_code do
    Enum.map(lib_sources(), fn source ->
      source
      |> String.replace(~r/"""[\s\S]*?"""/, "")
      |> String.split("\n")
      |> Enum.reject(&String.starts_with?(String.trim_leading(&1), "#"))
      |> Enum.join("\n")
    end)
  end

  # The AST, not a regular expression over the source text. The expression this
  # replaces could only see a LITERAL event name, so an event emitted through a
  # module attribute was invisible to it in both directions: it could not be
  # found, and documenting it failed the check above with "documented in
  # docs/api.md but not emitted anywhere in lib/" (`open-findings.md` X222).
  # Three emit sites in this package still carry a comment saying the name is
  # written out longhand to keep that expression happy.
  defp telemetry_sites do
    lib_root()
    |> TelemetryCensus.sites()
    |> Enum.map(&TelemetryCensus.render(&1.event))
  end

  # A telemetry literal must be an emit site, not merely text: a documented
  # event that survives only in prose is the failure this catches.
  defp present?("[:aurora_meter" <> _ = literal, sites, _code), do: literal in sites
  defp present?(literal, _sites, code), do: Enum.any?(code, &String.contains?(&1, literal))

  defp from_lib?(module) do
    Code.ensure_loaded?(module) and
      case module.module_info(:compile)[:source] do
        nil -> false
        source -> source |> List.to_string() |> String.starts_with?(lib_root())
      end
  end

  defp module_present?(module), do: Code.ensure_loaded?(module)

  defp exported?(module, fun, arity) do
    Code.ensure_loaded?(module) and
      (function_exported?(module, fun, arity) or macro_exported?(module, fun, arity))
  end

  defp moduledoc(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, doc, _, _} -> doc
      _ -> :none
    end
  end

  defp doc_for(module, fun, arity) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, _, _, docs} ->
        Enum.find_value(docs, :none, fn
          {{kind, ^fun, ^arity}, _, _, doc, _} when kind in [:function, :macro] -> doc
          _ -> false
        end)

      _ ->
        :none
    end
  end

  defp hidden?(module, fun, arity), do: doc_for(module, fun, arity) == :hidden

  # One entry per *definition*: a function with default arguments appears once,
  # at its maximum arity, which is the arity the `@spec` covers.
  defp public_entries(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, _, _, docs} ->
        for {{kind, name, arity}, _anno, _sig, doc, _meta} <- docs,
            kind in [:function, :macro],
            doc != :hidden,
            not reflection?(name),
            do: {kind, name, arity}

      _ ->
        []
    end
  end

  defp reflection?(name) do
    name = Atom.to_string(name)
    String.starts_with?(name, "__") and String.ends_with?(name, "__")
  end

  defp spec?(module, {:function, name, arity}), do: has_spec?(module, name, arity)
  defp spec?(module, {:macro, name, arity}), do: has_spec?(module, :"MACRO-#{name}", arity + 1)

  defp has_spec?(module, name, arity) do
    case Code.Typespec.fetch_specs(module) do
      {:ok, specs} -> Enum.any?(specs, fn {{n, a}, _} -> n == name and a == arity end)
      _ -> false
    end
  end

  defp excepted?(module, {_kind, name, arity}) do
    Enum.any?(@spec_exceptions, fn {m, f, a, _reason} ->
      m == module and f == name and a == arity
    end)
  end

  defp describe_entry(module, {kind, name, arity}),
    do: "#{inspect(module)}.#{name}/#{arity} (#{kind})"

  defp format_entry({module, fun, arity}), do: "#{inspect(module)}.#{fun}/#{arity}"

  defp lines(entries) do
    Enum.map_join(entries, "\n", fn {line, text} ->
      if line > 0, do: "  #{@inventory}:#{line}  #{text}", else: "  #{text}"
    end)
  end

  # -- A06: the documented signature against the real @spec ------------------

  # The "Signature and return" cell, as text, with the escaped pipes a markdown
  # table needs turned back into the union bars they stand for.
  defp signature_cell(row) do
    with cell when is_binary(cell) <- Enum.at(row.cells, 1),
         [_, text] <- Regex.run(~r/^`(.+)`$/s, cell) do
      String.replace(text, "\\|", "|")
    else
      _ -> nil
    end
  end

  # "(a, b) :: c" -> 2. `nil` when the cell is not in that shape at all, which
  # is how a prose cell opts out rather than failing with a confusing message.
  defp documented_arity(row) do
    with text when is_binary(text) <- signature_cell(row),
         [_, args] <- Regex.run(~r/^\((.*?)\)\s*::/s, text) do
      case String.trim(args) do
        "" -> 0
        args -> length(split_top_level(args))
      end
    else
      _ -> nil
    end
  end

  defp split_top_level(text) do
    text
    |> String.graphemes()
    |> Enum.reduce({0, "", []}, fn char, {depth, current, done} ->
      cond do
        char in ["(", "[", "{"] -> {depth + 1, current <> char, done}
        char in [")", "]", "}"] -> {depth - 1, current <> char, done}
        char == "," and depth == 0 -> {depth, "", [current | done]}
        true -> {depth, current <> char, done}
      end
    end)
    |> then(fn {_depth, current, done} -> Enum.reverse([current | done]) end)
  end

  # One return-type string per `@spec` clause. A function with two clauses has
  # two, and they are compared as a union, because a caller can receive either.
  defp spec_returns(module, fun, arity) do
    with true <- Code.ensure_loaded?(module),
         {:ok, specs} <- Code.Typespec.fetch_specs(module),
         {_key, forms} <- Enum.find(specs, fn {{f, a}, _} -> f == fun and a == arity end) do
      Enum.map(forms, fn form ->
        fun |> Code.Typespec.spec_to_quoted(form) |> Macro.to_string()
      end)
    else
      _ -> nil
    end
  end

  # The atoms a caller can pattern match on: the atom members of the top-level
  # union, the leading atom of each top-level tuple, and (one level deeper) the
  # tag inside a tuple such as `{:error, :not_configured}` or
  # `{:error, {:unsupported, capability()}}`. A named type met at one of those
  # positions is resolved, so `{:error, error()}` and the union `error()` stands
  # for are the same surface, whichever side writes which.
  #
  # Deliberately NOT every atom in the type. The inventory abbreviates on
  # purpose: it prints `map()` where the spec names a struct or a report type,
  # and that is a readability decision rather than a defect. A comparison that
  # failed those would be noise somebody eventually switches off. What it must
  # not miss is the match surface, which is where X370 lived: an error tag the
  # spec can return and the table does not print is a `case` clause a reader
  # will not write.
  #
  # `:unparsable` when the text is not a type expression, which is how a prose
  # cell opts out rather than being guessed at.
  defp match_atoms(text, module) do
    return =
      text
      |> String.split("::", parts: 2)
      |> List.last()
      |> String.split(~r/\bwhen\b/, parts: 2)
      |> List.first()

    case Code.string_to_quoted(return) do
      {:ok, ast} ->
        ast
        |> union_members(module)
        |> Enum.flat_map(&member_atoms(&1, 1, module))
        |> MapSet.new()

      _ ->
        :unparsable
    end
  end

  # Flattens `a | b` and resolves a named type into the union it stands for.
  # Bounded, because a recursive type would not otherwise terminate.
  defp union_members(node, module, depth \\ 2)

  defp union_members({:|, _meta, [left, right]}, module, depth),
    do: union_members(left, module, depth) ++ union_members(right, module, depth)

  defp union_members(node, module, depth) when depth > 0 do
    case resolve_type(node, module) do
      nil -> [node]
      resolved -> union_members(resolved, module, depth - 1)
    end
  end

  defp union_members(node, _module, _depth), do: [node]

  defp resolve_type({name, _meta, []}, module) when is_atom(name) and module != nil,
    do: type_definition(module, name)

  defp resolve_type({{:., _, [{:__aliases__, _, parts}, name]}, _meta, []}, _module),
    do: type_definition(Module.concat(parts), name)

  defp resolve_type(_node, _module), do: nil

  defp type_definition(module, name) do
    with true <- Code.ensure_loaded?(module),
         {:ok, types} <- Code.Typespec.fetch_types(module),
         {_kind, type} <-
           Enum.find(types, fn {kind, {n, _definition, args}} ->
             kind in [:type, :opaque] and n == name and args == []
           end),
         {:"::", _meta, [_head, definition]} <- Code.Typespec.type_to_quoted(type) do
      definition
    else
      _ -> nil
    end
  end

  defp member_atoms(node, depth, module) do
    node
    |> union_members(module)
    |> Enum.flat_map(&single_member_atoms(&1, depth, module))
  end

  defp single_member_atoms(atom, _depth, _module) when is_atom(atom), do: [atom]

  defp single_member_atoms({:{}, _meta, elements}, depth, module),
    do: tuple_atoms(elements, depth, module)

  defp single_member_atoms({left, right}, depth, module),
    do: tuple_atoms([left, right], depth, module)

  defp single_member_atoms(_other, _depth, _module), do: []

  defp tuple_atoms([], _depth, _module), do: []

  defp tuple_atoms([first | rest], depth, module) do
    head = first |> union_members(module) |> Enum.filter(&is_atom/1)
    tail = if depth > 0, do: Enum.flat_map(rest, &member_atoms(&1, depth - 1, module)), else: []
    head ++ tail
  end

  # {atoms the spec can return and the table does not print,
  #  atoms the table prints and the spec cannot return}, both sorted.
  # `:unparsable` when either side is not a type expression.
  defp atom_difference(documented, spec_returns, module \\ nil)

  defp atom_difference(documented, spec_returns, module) when is_list(spec_returns) do
    doc_atoms = match_atoms(documented, module)

    spec_atoms =
      Enum.reduce_while(spec_returns, MapSet.new(), fn clause, acc ->
        case match_atoms(clause, module) do
          :unparsable -> {:halt, :unparsable}
          atoms -> {:cont, MapSet.union(acc, atoms)}
        end
      end)

    if doc_atoms == :unparsable or spec_atoms == :unparsable do
      :unparsable
    else
      {
        spec_atoms |> MapSet.difference(doc_atoms) |> MapSet.to_list() |> Enum.sort(),
        doc_atoms |> MapSet.difference(spec_atoms) |> MapSet.to_list() |> Enum.sort()
      }
    end
  end

  defp atom_difference(documented, spec, module) when is_binary(spec),
    do: atom_difference(documented, [spec], module)

  # -- A07: examples that nothing runs ---------------------------------------

  # Read from the test sources as AST. A `doctest Foo` is a call; the same words
  # in a moduledoc are a string, and a grep cannot tell them apart
  # (open-findings.md X84, which DocsClaimsTest records for the same reason).
  defp doctested_modules do
    "test/**/*.exs"
    |> Path.wildcard()
    |> Enum.flat_map(fn path ->
      path
      |> File.read!()
      |> Code.string_to_quoted!(file: path)
      |> Macro.prewalk([], fn
        {:doctest, _meta, [{:__aliases__, _, parts} | _]} = node, acc ->
          {node, [Module.concat(parts) | acc]}

        node, acc ->
          {node, acc}
      end)
      |> elem(1)
    end)
    |> MapSet.new()
  end

  defp has_iex_example?(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, moduledoc, _, docs} ->
        contains_iex?(moduledoc) or
          Enum.any?(docs, fn {_key, _anno, _sig, doc, _meta} -> contains_iex?(doc) end)

      _ ->
        false
    end
  end

  defp contains_iex?(%{} = doc), do: doc |> Map.values() |> Enum.any?(&contains_iex?/1)
  defp contains_iex?(text) when is_binary(text), do: String.contains?(text, "iex>")
  defp contains_iex?(_), do: false
end
