defmodule AuroraMeter.ApiInventoryTest do
  @moduledoc """
  Guards the published API inventory in `docs/api.md`.

  Five unit-local invariants, named in build unit 02a:

    * A01: every `Module.function/arity` listed in `docs/api.md` exists at
      runtime, except rows tagged `optional-dep` whose module is absent.
    * A02: nothing internal (`@doc false`, or a module in `@internal_modules`)
      appears in `docs/api.md`.
    * A03: every non-internal module under `lib/` carries a real `@moduledoc`.
    * A04: every public function of a non-internal module carries a `@spec`,
      unless it is listed in `@spec_exceptions` with a reason.
    * A05: every telemetry event and PubSub tag documented in `docs/api.md`
      appears verbatim in `lib/`.

  The test reflects on compiled modules and reads `docs/api.md` as text. It
  touches no database and starts nothing, so it is `async: true`.

  `docs/api.md` is parsed by the HTML comments `<!-- inventory:<mode> -->`.
  Everything before the first one, and everything in an `inventory:none`
  region, is prose. Inside a region, the first row of each table is its header
  and every later row must carry a single inline-code span in its first cell.
  """
  use ExUnit.Case, async: true

  @inventory "docs/api.md"

  # The internal set fixed by `api-change-map.md` section 1.8 and section 6.2,
  # restricted to modules that exist in this release. It is the single source of
  # truth for A02, A03 and A04, it is the "Internal modules" section of
  # `docs/api.md`, and `mix.exs`'s "Internal" module group must equal it.
  @internal_modules [
    AuroraMeter.BootChecks,
    AuroraMeter.Broadcaster,
    AuroraMeter.Cluster,
    AuroraMeter.Config.Schema,
    AuroraMeter.Counter,
    AuroraMeter.Credits.Ledger,
    AuroraMeter.Credits.Promotions,
    AuroraMeter.Credits.Reconciliation,
    AuroraMeter.Credits.Series,
    AuroraMeter.Events.Backfill,
    AuroraMeter.Events.Canonical,
    AuroraMeter.Events.Gate,
    AuroraMeter.Install.Templates,
    AuroraMeter.Migration.V1,
    AuroraMeter.Migration.V2,
    AuroraMeter.Migration.V3,
    AuroraMeter.Migration.V4,
    AuroraMeter.Migration.V5,
    AuroraMeter.Migration.V6,
    AuroraMeter.Migration.V7,
    AuroraMeter.Migration.V8,
    AuroraMeter.Schema.FlushReceipt,
    AuroraMeter.Storage.Ecto,
    AuroraMeter.Store,
    AuroraMeter.Supervisor
  ]

  # The one entry of an internal module that `docs/api.md` is allowed to list,
  # because a host has to build the topic string to subscribe to it.
  # `api-change-map.md` 1.8: "keep `topic/1` documented".
  @internal_carve_outs [{AuroraMeter.Broadcaster, :topic, 1}]

  # Functions of internal modules that must keep a real `@doc` even though the
  # module is internal, because a host or the test helpers still call them.
  @must_stay_documented [
    {AuroraMeter.Flusher, :flush, 0},
    {AuroraMeter.Broadcaster, :topic, 1},
    {AuroraMeter.Subscriptions, :get, 1},
    {AuroraMeter.Subscriptions, :invalidate, 1},
    {AuroraMeter.Cluster, :apply, 3}
  ]

  # `{module, function, arity, reason}`. A04 fails when an entry carries no
  # reason and when an entry is no longer needed, so the list cannot rot.
  @spec_exceptions [
    {AuroraMeter.Clock.Fixed, :child_spec, 1,
     "generated by `use Agent`; the contract is OTP's `Supervisor.child_spec/0` " <>
       "and a hand-written spec here would restate it at the risk of drifting from it"},
    {AuroraMeter.Flusher, :child_spec, 1,
     "generated by `use GenServer`; same reason as `AuroraMeter.Clock.Fixed.child_spec/1`"},
    {AuroraMeter.Components, :usage_meter, 1,
     "HEEx function component: the typed contract is its `attr/3` declarations, which " <>
       "ExDoc renders, and its return type belongs to an optional dependency"},
    {AuroraMeter.Components, :usage_summary, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.Components, :spend_chart, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.Components, :credit_summary, 1, "HEEx function component, as `usage_meter/1`"},
    {AuroraMeter.Plans, :plan, 2,
     "plans DSL macro: it is usable only inside a module that `use`s `AuroraMeter.Plans`, " <>
       "and a spec would describe the AST it receives rather than the DSL it accepts"},
    {AuroraMeter.Plans, :price, 1, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :limit, 3, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :metered, 2, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :feature, 2, "plans DSL macro, as `plan/2`"},
    {AuroraMeter.Plans, :counter, 1, "plans DSL macro, as `plan/2`"}
  ]

  setup_all do
    %{regions: parse_inventory(@inventory)}
  end

  describe "A01 the inventory resolves" do
    test "every function listed in docs/api.md exists", %{regions: regions} do
      missing =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            module_present?(module) or not optional_dep?(row),
            not exported?(module, fun, arity),
            do: {row.line, format_entry(entry)}

      assert missing == [], "docs/api.md names functions that do not exist:\n" <> lines(missing)
    end

    test "every module listed in docs/api.md exists", %{regions: regions} do
      missing =
        for row <- rows(regions, :modules) ++ rows(regions, :internal),
            module = module_entry!(row),
            not optional_dep?(row) or module_present?(module),
            not module_present?(module),
            do: {row.line, inspect(module)}

      assert missing == [], "docs/api.md names modules that do not exist:\n" <> lines(missing)
    end

    test "optional-dependency rows are tagged, and skipped only when the module is absent",
         %{regions: regions} do
      optional = Enum.filter(rows(regions, :functions), &optional_dep?/1)

      assert optional != [],
             "no row in docs/api.md is tagged optional-dep, so the tag has rotted away"

      skipped =
        Enum.reject(optional, fn row ->
          {module, _, _} = function_entry!(row)
          module_present?(module)
        end)

      if Code.ensure_loaded?(Phoenix.Component) do
        assert skipped == [],
               "Phoenix.Component is loaded, so no optional-dep row should have been skipped"
      else
        assert skipped != [],
               "this is a headless build (no Phoenix.Component) and no optional-dep row " <>
                 "was skipped, so the skip path is not being exercised"
      end
    end

    test "every documented configuration key is in the schema", %{regions: regions} do
      known = Keyword.keys(AuroraMeter.Config.schema().schema)

      documented =
        for row <- rows(regions, :config) do
          row |> first_code_span!() |> String.trim_leading(":") |> String.to_atom()
        end

      assert documented != [], "docs/api.md documents no configuration key"
      assert documented -- known == [], "documented keys that the schema does not declare"
      assert known -- documented == [], "schema keys that docs/api.md does not document"
    end
  end

  describe "A02 the inventory excludes what is internal" do
    test "no module marked internal appears in the inventory", %{regions: regions} do
      offenders =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            module in @internal_modules,
            {module, fun, arity} not in @internal_carve_outs,
            do: {row.line, format_entry(entry)}

      module_rows =
        for row <- rows(regions, :modules),
            module = module_entry!(row),
            module in @internal_modules,
            # A module row may name an internal module as long as it says so.
            not String.contains?(row.raw, "internal"),
            do: {row.line, inspect(module)}

      assert offenders ++ module_rows == [],
             "internal entries listed as supported API:\n" <> lines(offenders ++ module_rows)
    end

    test "no @doc false function appears in the inventory", %{regions: regions} do
      offenders =
        for row <- rows(regions, :functions),
            {module, fun, arity} = entry = function_entry!(row),
            module_present?(module),
            hidden?(module, fun, arity),
            do: {row.line, format_entry(entry)}

      assert offenders == [],
             "docs/api.md lists functions carrying @doc false:\n" <> lines(offenders)
    end

    test "the internal section and @internal_modules are the same list", %{regions: regions} do
      documented = regions |> rows(:internal) |> Enum.map(&module_entry!/1) |> Enum.sort()

      assert documented == Enum.sort(@internal_modules),
             "the \"Internal modules\" section of docs/api.md and @internal_modules disagree"
    end

    test "mix.exs puts exactly @internal_modules in the Internal docs group" do
      groups = Mix.Project.config()[:docs][:groups_for_modules] || []
      internal = groups |> Keyword.get(:Internal, []) |> Enum.sort()

      assert internal == Enum.sort(@internal_modules),
             "mix.exs groups_for_modules[:Internal] and @internal_modules disagree"
    end

    test "internal modules keep the entries a host still calls documented" do
      undocumented =
        for {module, fun, arity} <- @must_stay_documented,
            doc_for(module, fun, arity) in [:none, :hidden],
            do: {0, "#{inspect(module)}.#{fun}/#{arity}"}

      assert undocumented == [],
             "these must keep a real @doc:\n" <> lines(undocumented)
    end

    test "every internal module carries the stability banner" do
      banner = "**Internal.**"

      missing =
        for module <- @internal_modules,
            %{} = doc <- [moduledoc(module)],
            not String.contains?(Map.get(doc, "en", ""), banner),
            do: {0, inspect(module)}

      assert missing == [],
             "internal modules whose @moduledoc lacks the stability banner:\n" <> lines(missing)
    end
  end

  describe "A03 moduledocs" do
    test "every non-internal module under lib/ has a moduledoc" do
      missing =
        for module <- lib_modules(),
            module not in @internal_modules,
            moduledoc(module) in [:none, :hidden],
            do: {0, "#{inspect(module)} (#{inspect(moduledoc(module))})"}

      assert missing == [], "modules without a @moduledoc:\n" <> lines(missing)
    end
  end

  describe "A04 specs" do
    test "every public function of a non-internal module has a spec" do
      missing =
        for module <- lib_modules(),
            module not in @internal_modules,
            entry <- public_entries(module),
            not spec?(module, entry),
            not excepted?(module, entry),
            do: {0, describe_entry(module, entry)}

      assert missing == [], "public functions without a @spec:\n" <> lines(missing)
    end

    test "every spec exception carries a reason" do
      for {module, fun, arity, reason} <- @spec_exceptions do
        assert is_binary(reason) and String.trim(reason) != "",
               "#{inspect(module)}.#{fun}/#{arity} is spec-excepted with no reason"
      end
    end

    test "no spec exception is stale" do
      stale =
        for {module, fun, arity, _reason} <- @spec_exceptions,
            module_present?(module),
            spec?(module, {:function, fun, arity}) or
              spec?(module, {:macro, fun, arity}) or
              ({:function, fun, arity} not in public_entries(module) and
                 {:macro, fun, arity} not in public_entries(module)),
            do: {0, "#{inspect(module)}.#{fun}/#{arity}"}

      assert stale == [], "spec exceptions that are no longer needed:\n" <> lines(stale)
    end
  end

  describe "A05 documented literals exist in lib/" do
    # Doc strings and comments are stripped first. Mentioning an event in a
    # moduledoc is not emitting it, and a check that accepted the mention would
    # pass for an event that had been renamed at the only place that matters.
    test "every telemetry event and PubSub tag appears verbatim in lib/ code",
         %{regions: regions} do
      sites = telemetry_sites()
      code = lib_code()

      missing =
        for row <- rows(regions, :literal),
            literal = literal!(row),
            not present?(literal, sites, code),
            do: {row.line, literal}

      assert missing == [],
             "documented in docs/api.md but not emitted anywhere in lib/:\n" <> lines(missing)
    end

    test "the literal sections name at least the events and messages that exist",
         %{regions: regions} do
      literals = regions |> rows(:literal) |> Enum.map(&literal!/1)

      telemetry = Enum.count(literals, &String.starts_with?(&1, "[:aurora_meter"))
      pubsub = Enum.count(literals, &String.starts_with?(&1, "{:aurora_meter"))

      assert telemetry == length(telemetry_sites()),
             "docs/api.md documents #{telemetry} telemetry events but lib/ emits " <>
               "#{length(telemetry_sites())}"

      assert pubsub >= 6, "docs/api.md documents only #{pubsub} PubSub messages"
    end
  end

  # -- inventory parsing -----------------------------------------------------

  defp parse_inventory(path) do
    path
    |> File.read!()
    |> String.split("\n")
    |> Enum.with_index(1)
    |> Enum.reduce({:none, :outside, [], []}, &parse_line/2)
    |> elem(2)
    |> Enum.reverse()
  end

  defp parse_line({line, number}, {mode, table, acc, header}) do
    cond do
      match = Regex.run(~r/^<!--\s*inventory:([a-z]+)\s*-->\s*$/, line) ->
        {String.to_atom(Enum.at(match, 1)), :outside, acc, []}

      not String.starts_with?(String.trim(line), "|") ->
        {mode, :outside, acc, header}

      table == :outside ->
        {mode, :header, acc, cells(line)}

      table == :header ->
        {mode, :body, acc, header}

      true ->
        row = %{mode: mode, line: number, raw: line, cells: cells(line), header: header}
        {mode, :body, [row | acc], header}
    end
  end

  defp cells(line) do
    line
    |> String.trim()
    |> String.trim_leading("|")
    |> String.trim_trailing("|")
    |> then(&Regex.split(~r/(?<!\\)\|/, &1))
    |> Enum.map(&String.trim/1)
  end

  defp rows(regions, mode), do: Enum.filter(regions, &(&1.mode == mode))

  defp first_code_span!(row) do
    cell = hd(row.cells)

    case Regex.run(~r/^`([^`]+)`$/, cell) do
      [_, text] ->
        text

      _ ->
        flunk(
          "docs/api.md line #{row.line}: the first cell of a row in an inventory section " <>
            "must be a single inline-code span, got #{inspect(cell)}"
        )
    end
  end

  defp function_entry!(row) do
    text = first_code_span!(row)

    case Regex.run(~r/^([A-Za-z0-9_.]+)\.([a-z_][A-Za-z0-9_?!]*)\/(\d+)$/, text) do
      [_, module, fun, arity] ->
        {Module.concat([module]), String.to_atom(fun), String.to_integer(arity)}

      _ ->
        flunk("docs/api.md line #{row.line}: expected `Module.function/arity`, got `#{text}`")
    end
  end

  defp module_entry!(row) do
    text = first_code_span!(row)

    unless Regex.match?(~r/^[A-Z][A-Za-z0-9_.]*$/, text) do
      flunk("docs/api.md line #{row.line}: expected a module name, got `#{text}`")
    end

    Module.concat([text])
  end

  @literal_column "Matched in lib/"

  # Literal rows carry the greppable source text in a column of their own, so
  # the human-readable event name in the first cell can differ from the source
  # (`[:aurora_meter, :credits, kind]` is emitted as `txn.kind`). The column is
  # found by its header text, never by its position (open-findings.md X67).
  defp literal!(row) do
    index =
      Enum.find_index(row.header, &(&1 == @literal_column)) ||
        flunk(
          "docs/api.md line #{row.line}: a literal table needs a #{inspect(@literal_column)} " <>
            "column, its header is #{inspect(row.header)}"
        )

    cell = Enum.at(row.cells, index, "")

    case Regex.run(~r/^`(.+)`$/, cell) do
      [_, text] ->
        String.replace(text, "\\|", "|")

      _ ->
        flunk(
          "docs/api.md line #{row.line}: the #{inspect(@literal_column)} cell must be a " <>
            "single inline-code span holding the source text, got #{inspect(cell)}"
        )
    end
  end

  defp optional_dep?(row), do: Enum.any?(row.cells, &(&1 == "optional-dep"))

  # -- reflection ------------------------------------------------------------

  defp lib_root, do: Path.expand("lib") <> "/"

  defp lib_modules do
    {:ok, modules} = :application.get_key(:aurora_meter, :modules)

    modules
    |> Enum.filter(&from_lib?/1)
    |> Enum.sort()
  end

  defp lib_sources do
    "lib/**/*.ex" |> Path.wildcard() |> Enum.map(&File.read!/1)
  end

  # `lib/` with every heredoc (which is every `@moduledoc` and `@doc`, plus the
  # installer's templates) and every whole-line comment removed, so a literal
  # found here is one the code actually uses.
  defp lib_code do
    Enum.map(lib_sources(), fn source ->
      source
      |> String.replace(~r/"""[\s\S]*?"""/, "")
      |> String.split("\n")
      |> Enum.reject(&String.starts_with?(String.trim_leading(&1), "#"))
      |> Enum.join("\n")
    end)
  end

  # `execute` and `span` both. A span is one emit site that produces three
  # events, and docs/api.md documents it as one row under its prefix, so the
  # counts line up. Reading only `execute` would have made the `record` span
  # invisible to this guard on the very run that introduced it.
  defp telemetry_sites do
    lib_code()
    |> Enum.flat_map(
      &Regex.scan(~r/:telemetry\.(?:execute|span)\(\s*(\[:aurora_meter[^\]]*\])/, &1)
    )
    |> Enum.map(&Enum.at(&1, 1))
  end

  # A telemetry literal must be an emit site, not merely text: a documented
  # event that survives only in prose is the failure this catches.
  defp present?("[:aurora_meter" <> _ = literal, sites, _code), do: literal in sites
  defp present?(literal, _sites, code), do: Enum.any?(code, &String.contains?(&1, literal))

  defp from_lib?(module) do
    Code.ensure_loaded?(module) and
      case module.module_info(:compile)[:source] do
        nil -> false
        source -> source |> List.to_string() |> String.starts_with?(lib_root())
      end
  end

  defp module_present?(module), do: Code.ensure_loaded?(module)

  defp exported?(module, fun, arity) do
    Code.ensure_loaded?(module) and
      (function_exported?(module, fun, arity) or macro_exported?(module, fun, arity))
  end

  defp moduledoc(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, doc, _, _} -> doc
      _ -> :none
    end
  end

  defp doc_for(module, fun, arity) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, _, _, docs} ->
        Enum.find_value(docs, :none, fn
          {{kind, ^fun, ^arity}, _, _, doc, _} when kind in [:function, :macro] -> doc
          _ -> false
        end)

      _ ->
        :none
    end
  end

  defp hidden?(module, fun, arity), do: doc_for(module, fun, arity) == :hidden

  # One entry per *definition*: a function with default arguments appears once,
  # at its maximum arity, which is the arity the `@spec` covers.
  defp public_entries(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _, _, _, _, _, docs} ->
        for {{kind, name, arity}, _anno, _sig, doc, _meta} <- docs,
            kind in [:function, :macro],
            doc != :hidden,
            not reflection?(name),
            do: {kind, name, arity}

      _ ->
        []
    end
  end

  defp reflection?(name) do
    name = Atom.to_string(name)
    String.starts_with?(name, "__") and String.ends_with?(name, "__")
  end

  defp spec?(module, {:function, name, arity}), do: has_spec?(module, name, arity)
  defp spec?(module, {:macro, name, arity}), do: has_spec?(module, :"MACRO-#{name}", arity + 1)

  defp has_spec?(module, name, arity) do
    case Code.Typespec.fetch_specs(module) do
      {:ok, specs} -> Enum.any?(specs, fn {{n, a}, _} -> n == name and a == arity end)
      _ -> false
    end
  end

  defp excepted?(module, {_kind, name, arity}) do
    Enum.any?(@spec_exceptions, fn {m, f, a, _reason} ->
      m == module and f == name and a == arity
    end)
  end

  defp describe_entry(module, {kind, name, arity}),
    do: "#{inspect(module)}.#{name}/#{arity} (#{kind})"

  defp format_entry({module, fun, arity}), do: "#{inspect(module)}.#{fun}/#{arity}"

  defp lines(entries) do
    Enum.map_join(entries, "\n", fn {line, text} ->
      if line > 0, do: "  #{@inventory}:#{line}  #{text}", else: "  #{text}"
    end)
  end
end
