defmodule AuroraMeter.CreditsReconcileHoldsTest.Releaser do
  @moduledoc false
  # A reconciler in each of the three configurable shapes: the module itself,
  # `{module, :decide}`, and `&Releaser.decide/1`.
  @behaviour AuroraMeter.Credits.HoldReconciler

  @impl AuroraMeter.Credits.HoldReconciler
  def decide(_hold), do: :release
end

defmodule AuroraMeter.CreditsReconcileHoldsTest do
  @moduledoc false
  # async: false. Several tests mutate `:aurora_meter` configuration, which is
  # node-wide, and a configuration region does not protect against a concurrent
  # reader (open-findings.md X165). The frozen clock is node-wide too.
  use AuroraMeter.DataCase, async: false

  # One test arms a fault point, so the whole module joins the `mix v1.faults`
  # lane (docs/testing.md).
  @moduletag :fault

  import AuroraMeter.Test, only: [fund!: 2, fund!: 3, with_clock: 2, travel: 2]
  import AuroraMeter.Test.Config, only: [with_config: 2]
  import ExUnit.CaptureLog

  alias AuroraMeter.Clock
  alias AuroraMeter.Config
  alias AuroraMeter.Credits
  alias AuroraMeter.Credits.Ledger
  alias AuroraMeter.CreditsReconcileHoldsTest.Releaser
  alias AuroraMeter.Schema.CreditTransaction
  alias AuroraMeter.Test.Faults
  alias AuroraMeter.Test.LedgerFixtures

  @dollar 1_000_000
  @event [:aurora_meter, :credits, :hold_reconciliation]

  @doc false
  def handle_event(event, measurements, metadata, %{parent: parent, tenant: tenant}) do
    if metadata.tenant_key == tenant,
      do: send(parent, {:telemetry, event, measurements, metadata})

    :ok
  end

  defp attach(tenant) do
    id = {__MODULE__, make_ref()}

    :ok =
      :telemetry.attach(id, @event, &__MODULE__.handle_event/4, %{
        parent: self(),
        tenant: tenant
      })

    on_exit(fn -> :telemetry.detach(id) end)
  end

  # A cutoff every hold taken so far is older than. A hold row's `inserted_at`
  # comes from Ecto's `timestamps/1` autogenerate, which is a node wall clock,
  # and `Clock.now/0` is a node wall clock too, so the two agree to well under
  # the second of headroom this leaves. The headroom is there because neither is
  # monotone.
  defp cutoff, do: DateTime.add(Clock.now(), 1, :second)

  defp hold!(tenant, amount, reference) do
    {:ok, txn} = Credits.hold(tenant, amount, reference)
    txn
  end

  # A pending hold row with an `inserted_at` this test chose. The ledger cannot
  # be asked for one: a credit row's `inserted_at` is autogenerated by Ecto's
  # `timestamps/1` and is not castable, so `AuroraMeter.Test.with_clock/2` does
  # not reach it. Only the tests whose subject is the timestamp itself use this;
  # everything else takes a real hold through the facade.
  defp insert_hold!(tenant, amount, reference, at) do
    %CreditTransaction{}
    |> Ecto.Changeset.change(%{
      tenant_key: tenant,
      kind: :hold,
      amount: 0,
      held_delta: amount,
      balance_after: 0,
      held_after: amount,
      promotional_after: 0,
      reference: reference,
      status: :pending,
      metadata: %{},
      inserted_at: at
    })
    |> TestRepo.insert!()
  end

  defp status(reference), do: Ledger.fetch_hold(reference).status

  defp entries(tenant, kind) do
    TestRepo.all(from(t in CreditTransaction, where: t.tenant_key == ^tenant and t.kind == ^kind))
  end

  defp rows(tenant) do
    TestRepo.aggregate(from(t in CreditTransaction, where: t.tenant_key == ^tenant), :count)
  end

  describe "the default" do
    test "keeps every hold when no reconciler is configured, and writes nothing" do
      # X171: where the confidence rests on a default, the default is part of
      # the claim. This asserts the shipped value as well as the behaviour, so a
      # future change to the default fails here rather than in production.
      assert Config.credits_hold_reconciler() == nil

      tenant = unique_tenant()
      fund!(tenant, 10 * @dollar)
      attach(tenant)

      for i <- 1..10, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")
      before = rows(tenant)

      assert {:ok, report} = Credits.reconcile_holds(older_than: cutoff())

      assert %{examined: 10, kept: 10, released: 0, settled: 0, already_closed: 0, failed: 0} =
               report

      assert rows(tenant) == before
      assert %{held: 1_000_000} = Credits.balance(tenant)

      for _ <- 1..10 do
        assert_received {:telemetry, @event, _measurements,
                         %{decision: :keep, outcome: :no_reconciler}}
      end
    end

    test "and the same holds are released once a reconciler is configured" do
      # The paired control for the test above. Without it "kept: 10" is also
      # what a reconciler that never runs would report, and the default would be
      # proved by a code path that does nothing (open-findings.md X125).
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      for i <- 1..3, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")

      with_config([{:aurora_meter, :credits_hold_reconciler, fn _hold -> :release end}], fn ->
        refute Config.credits_hold_reconciler() == nil

        assert {:ok, %{examined: 3, released: 3, kept: 0}} =
                 Credits.reconcile_holds(older_than: cutoff())
      end)

      assert length(entries(tenant, :release)) == 3
      assert %{held: 0, balance: @dollar} = Credits.balance(tenant)
    end

    test "reconcile_holds/1 refuses to run without :older_than" do
      # L05b-4: age is an input, never a decision, and a sweep with no cutoff is
      # a sweep over every open hold in the table. The caller says so out loud.
      assert_raise KeyError, fn -> Credits.reconcile_holds([]) end
    end

    test "raises, naming the supervision tree, when AuroraMeter.TaskSupervisor is not running" do
      pid = Process.whereis(AuroraMeter.TaskSupervisor)
      Process.unregister(AuroraMeter.TaskSupervisor)

      try do
        message =
          assert_raise(RuntimeError, fn -> Credits.reconcile_holds(older_than: cutoff()) end).message

        assert message =~ "AuroraMeter.TaskSupervisor"
        assert message =~ "children"
      after
        Process.register(pid, AuroraMeter.TaskSupervisor)
      end
    end
  end

  describe "a callback that misbehaves" do
    test "keeps the hold and reports :callback_exit when it raises" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 100_000, "j:#{tenant}")
      attach(tenant)

      log =
        capture_log(fn ->
          assert {:ok, %{examined: 1, kept: 1, released: 0, settled: 0}} =
                   Credits.reconcile_holds(
                     older_than: cutoff(),
                     reconciler: fn _hold -> raise "the host's callback is broken" end
                   )
        end)

      assert status("j:#{tenant}") == :pending
      assert %{held: 100_000} = Credits.balance(tenant)
      assert log =~ tenant
      assert log =~ "j:#{tenant}"

      assert_received {:telemetry, @event, %{amount: 100_000},
                       %{decision: :keep, outcome: :callback_exit}}
    end

    test "keeps the hold and reports :callback_exit when it exits or throws" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 100_000, "e:#{tenant}")
      hold!(tenant, 100_000, "t:#{tenant}")

      capture_log(fn ->
        assert {:ok, %{examined: 2, kept: 2}} =
                 Credits.reconcile_holds(
                   older_than: cutoff(),
                   reconciler: fn
                     %{reference: "e:" <> _} -> exit(:bye)
                     %{reference: "t:" <> _} -> throw(:ball)
                   end
                 )
      end)

      assert status("e:#{tenant}") == :pending
      assert status("t:#{tenant}") == :pending
    end

    test "keeps the hold and reports :callback_timeout when it never answers" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      for i <- 1..2, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")
      attach(tenant)

      # A `receive` that cannot match, not a sleep (docs/testing.md rule 2). The
      # point is a callback that never answers, and the reconciler's brutal kill
      # is what ends it.
      blocked = fn _hold -> receive do: (:never -> :keep) end

      started = System.monotonic_time(:millisecond)

      log =
        capture_log(fn ->
          with_config([{:aurora_meter, :credits_hold_reconciler_timeout, 60}], fn ->
            assert {:ok, %{examined: 2, kept: 2, released: 0, settled: 0}} =
                     Credits.reconcile_holds(older_than: cutoff(), reconciler: blocked)
          end)
        end)

      elapsed = System.monotonic_time(:millisecond) - started

      # One timeout per hold, and bounded: the run does not wait for a callback
      # that will never answer, and it does not give up before the timeout.
      assert elapsed >= 120
      assert elapsed < 5_000

      assert status("j1:#{tenant}") == :pending
      assert status("j2:#{tenant}") == :pending
      assert log =~ "did not answer within 60ms"

      for _ <- 1..2 do
        assert_received {:telemetry, @event, _measurements,
                         %{decision: :keep, outcome: :callback_timeout}}
      end
    end

    test "keeps the hold and reports :callback_invalid for a value that is not a decision" do
      tenant = unique_tenant()
      fund!(tenant, 10 * @dollar)
      attach(tenant)

      returns = [:ok, {:settle, -1}, {:settle, 1.5}, nil, {:release, 5}, "release", :released]
      last = length(returns) - 1

      for i <- 0..last, do: hold!(tenant, 100_000, "v#{i}:#{tenant}")

      log =
        capture_log(fn ->
          assert {:ok, report} =
                   Credits.reconcile_holds(
                     older_than: cutoff(),
                     reconciler: fn %{reference: "v" <> rest} ->
                       {index, _} = rest |> String.split(":") |> hd() |> Integer.parse()
                       Enum.at(returns, index)
                     end
                   )

          assert report.examined == length(returns)
          assert report.kept == length(returns)
          assert report.released == 0
          assert report.settled == 0
        end)

      for {value, i} <- Enum.with_index(returns) do
        assert status("v#{i}:#{tenant}") == :pending
        assert log =~ inspect(value)
      end

      assert Credits.balance(tenant).held == length(returns) * 100_000
    end
  end

  describe "decisions" do
    test "releases only the holds the callback names" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      for i <- 1..3, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")

      assert {:ok, %{examined: 3, released: 1, kept: 2, settled: 0, already_closed: 0, failed: 0}} =
               Credits.reconcile_holds(
                 older_than: cutoff(),
                 reconciler: fn
                   %{reference: "j2:" <> _} -> :release
                   _hold -> :keep
                 end
               )

      assert length(entries(tenant, :release)) == 1
      assert status("j1:#{tenant}") == :pending
      assert status("j2:#{tenant}") == :released
      assert status("j3:#{tenant}") == :pending
      assert %{held: 200_000, balance: @dollar} = Credits.balance(tenant)
    end

    test "settles for the callback's amount, and reports the reserved amount beside it" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      attach(tenant)

      assert {:ok, %{examined: 1, settled: 1, released: 0, kept: 0}} =
               Credits.reconcile_holds(
                 older_than: cutoff(),
                 reconciler: fn _hold -> {:settle, 250_000} end
               )

      assert [%CreditTransaction{settled_amount: 250_000, amount: -250_000}] =
               entries(tenant, :settle)

      assert status("j:#{tenant}") == :settled
      assert %{held: 0, balance: 750_000} = Credits.balance(tenant)

      # Both numbers are on the event, so a policy that settles for the wrong
      # amount is visible as a drift between them rather than invisible.
      assert_received {:telemetry, @event, %{amount: 400_000},
                       %{decision: {:settle, 250_000}, outcome: :settled}}
    end

    test "{:settle, 0} closes the hold as settled rather than released" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")

      assert {:ok, %{settled: 1}} =
               Credits.reconcile_holds(
                 older_than: cutoff(),
                 reconciler: fn _hold -> {:settle, 0} end
               )

      assert status("j:#{tenant}") == :settled
      assert entries(tenant, :release) == []
      assert %{held: 0, balance: @dollar} = Credits.balance(tenant)
    end

    test "accepts a module, a {module, function} pair and a function" do
      for {shape, i} <- Enum.with_index([Releaser, {Releaser, :decide}, &Releaser.decide/1]) do
        tenant = unique_tenant()
        fund!(tenant, @dollar)
        hold!(tenant, 100_000, "j#{i}:#{tenant}")

        assert {:ok, %{released: 1}} =
                 Credits.reconcile_holds(older_than: cutoff(), reconciler: shape)

        assert status("j#{i}:#{tenant}") == :released
      end
    end

    test "hands the callback the tenant, the reference, the reserved amount and the metadata" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      {:ok, _} = Credits.hold(tenant, 123_000, "j:#{tenant}", metadata: %{"model" => "large"})

      parent = self()

      assert {:ok, %{kept: 1}} =
               Credits.reconcile_holds(
                 older_than: cutoff(),
                 reconciler: fn hold -> send(parent, {:asked, hold}) && :keep end
               )

      assert_received {:asked, hold}
      assert hold.tenant_key == tenant
      assert hold.reference == "j:#{tenant}"
      assert hold.amount == 123_000
      assert hold.metadata == %{"model" => "large"}
      assert %DateTime{} = hold.held_at
      assert hold.age_seconds >= 0
    end

    test "reports a cursor only when the page was full" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      for i <- 1..3, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")

      assert {:ok, %{examined: 2, cursor: {%DateTime{}, id}}} =
               Credits.reconcile_holds(older_than: cutoff(), tenant: tenant, limit: 2)

      assert is_binary(id)

      # Exactly a full page still gets a cursor: the run cannot tell a page that
      # emptied the table from one that stopped at the limit, and inventing
      # `nil` here would leave a hold unexamined for a caller that pages.
      assert {:ok, %{examined: 3, cursor: {%DateTime{}, _id}}} =
               Credits.reconcile_holds(older_than: cutoff(), tenant: tenant, limit: 3)

      assert {:ok, %{examined: 3, cursor: nil}} =
               Credits.reconcile_holds(older_than: cutoff(), tenant: tenant, limit: 10)
    end

    test "a hold kept on every run is still pending and still reserved after twenty runs" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      before = rows(tenant)

      for _ <- 1..20 do
        assert {:ok, %{examined: 1, kept: 1}} =
                 Credits.reconcile_holds(
                   older_than: cutoff(),
                   tenant: tenant,
                   reconciler: fn _hold -> :keep end
                 )
      end

      assert status("j:#{tenant}") == :pending
      assert rows(tenant) == before
      assert %{held: 400_000, balance: @dollar, available: 600_000} = Credits.balance(tenant)
    end

    test "uses one instant for every age in a run" do
      tenant = unique_tenant()
      parent = self()
      t0 = ~U[2026-03-01 00:00:00.000000Z]

      # Written straight into the table with the instants this test needs.
      # `AuroraMeter.Test.with_clock/2` cannot supply them: a credit ledger row's
      # `inserted_at` does not come from the configured clock at all (see the
      # finding recorded in docs/evidence/v1/phase-05/05b-hold-recovery.md), so
      # freezing the clock and taking a hold produces today's timestamp.
      insert_hold!(tenant, 100_000, "old:#{tenant}", t0)
      insert_hold!(tenant, 100_000, "new:#{tenant}", DateTime.add(t0, 100, :second))

      old_reference = "old:#{tenant}"
      new_reference = "new:#{tenant}"

      # The discriminating part: the first callback moves the clock a thousand
      # seconds. If the run read "now" once per hold rather than once per run,
      # the second hold's age would jump by the same thousand.
      reconciler = fn hold ->
        send(parent, {:age, hold.reference, hold.age_seconds})
        if hold.reference == old_reference, do: travel(1000, :second)
        :keep
      end

      with_clock(DateTime.add(t0, 300, :second), fn ->
        assert {:ok, %{examined: 2, kept: 2}} =
                 Credits.reconcile_holds(
                   older_than: DateTime.add(Clock.now(), 1, :second),
                   tenant: tenant,
                   reconciler: reconciler
                 )
      end)

      assert_received {:age, ^old_reference, 300}
      assert_received {:age, ^new_reference, 200}
    end

    test "reports an age of zero rather than a negative one when the clock disagrees" do
      # Two node clocks stamp and read a hold's `inserted_at`, and neither is
      # monotone (open-findings.md X100). A hold that looks as though it was
      # taken in the future is a clock disagreeing with itself, and the
      # behaviour promises `non_neg_integer`.
      tenant = unique_tenant()
      t0 = ~U[2026-03-01 00:00:00.000000Z]
      insert_hold!(tenant, 100_000, "future:#{tenant}", DateTime.add(t0, 500, :second))
      parent = self()

      with_clock(t0, fn ->
        assert {:ok, %{examined: 1, kept: 1}} =
                 Credits.reconcile_holds(
                   older_than: DateTime.add(Clock.now(), 600, :second),
                   tenant: tenant,
                   reconciler: fn hold -> send(parent, {:age, hold.age_seconds}) && :keep end
                 )
      end)

      assert_received {:age, 0}
    end
  end

  describe "failure inside a run" do
    test "counts a failing application without stopping the run" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      for i <- 1..3, do: hold!(tenant, 100_000, "j#{i}:#{tenant}")

      capture_log(fn ->
        with_config([{:aurora_meter, :repo, AuroraMeter.Test.FaultRepo}], fn ->
          # The first write of the run, which is the release of j1: the callback
          # keeps nothing, so j1 is the first hold a decision is applied to.
          Faults.arm(:before_commit, :raise,
            when: &(&1[:statement] == :transaction_insert and &1[:kind] == :write),
            count: 1,
            label: :release_write_fails
          )

          assert {:ok, %{examined: 3, released: 2, failed: 1, kept: 0}} =
                   Credits.reconcile_holds(
                     older_than: cutoff(),
                     tenant: tenant,
                     reconciler: fn _hold -> :release end
                   )

          Faults.assert_fired!(:before_commit)
        end)
      end)

      # The failed hold is untouched and the two behind it were still examined.
      assert status("j1:#{tenant}") == :pending
      assert status("j2:#{tenant}") == :released
      assert status("j3:#{tenant}") == :released
      assert length(entries(tenant, :release)) == 2
      assert %{held: 100_000} = Credits.balance(tenant)
    end
  end

  describe "the tenant guard" do
    test "settle/3 with a mismatched :tenant returns :not_found and writes nothing" do
      tenant = unique_tenant()
      other = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      before = rows(tenant)

      assert {:error, :not_found} = Credits.settle("j:#{tenant}", 250_000, tenant: other)

      assert status("j:#{tenant}") == :pending
      assert rows(tenant) == before
      assert %{held: 400_000, balance: @dollar} = Credits.balance(tenant)

      # The paired control. Without it, `:not_found` is also what a reference
      # that never existed returns, and the guard would be proved by a hold the
      # test failed to create (open-findings.md X125, and 04f's 9a/9b shape).
      assert {:ok, _txn} = Credits.settle("j:#{tenant}", 250_000, tenant: tenant)
      assert status("j:#{tenant}") == :settled
    end

    test "release/2 with a mismatched :tenant returns :not_found and writes nothing" do
      tenant = unique_tenant()
      other = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      before = rows(tenant)

      assert {:error, :not_found} = Credits.release("j:#{tenant}", tenant: other)

      assert status("j:#{tenant}") == :pending
      assert rows(tenant) == before

      assert {:ok, _txn} = Credits.release("j:#{tenant}", tenant: tenant)
      assert status("j:#{tenant}") == :released
    end

    test "settle/3 and release/2 without :tenant behave exactly as before" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "s:#{tenant}")
      hold!(tenant, 100_000, "r:#{tenant}")

      assert {:ok, %CreditTransaction{amount: -250_000}} = Credits.settle("s:#{tenant}", 250_000)
      assert {:ok, %CreditTransaction{kind: :release}} = Credits.release("r:#{tenant}")
      assert {:error, :already_settled} = Credits.settle("s:#{tenant}", 1)
      assert {:error, :not_found} = Credits.release("nothing:#{tenant}")
      assert %{held: 0, balance: 750_000} = Credits.balance(tenant)
    end

    test "a mismatched :tenant on an already closed hold is also :not_found" do
      tenant = unique_tenant()
      other = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      {:ok, _} = Credits.settle("j:#{tenant}", 100_000)

      # Not `:already_settled`: to a caller that named the wrong tenant this
      # hold does not exist, and saying "already settled" would confirm that a
      # reference it has no business knowing about is in use.
      assert {:error, :not_found} = Credits.settle("j:#{tenant}", 1, tenant: other)
    end
  end

  describe "recovery beside expiry" do
    test "I12 a reconciler release on an expired grant returns spendable credit (L1, fixed in 06a)" do
      # The reconciler's version of `AuroraMeter.CreditsTest`'s L1 test. A
      # recovery decision must not weaken the guarantee holds carry (D09), so
      # the value a released hold returns is exactly what `Credits.release/2`
      # returns and nothing else: this unit adds no arithmetic of its own.
      #
      # That value is spendable although the grant it came from expired, which
      # is open finding L1. **The lot model landed and the expectation did not
      # flip here; it forked.** On a wallet the allocator owns the released
      # reservation becomes `expired` and never spendable, which is asserted by
      # `credits_lots_test.exs` / `test I12 a reservation released on an expired
      # lot becomes expired, never spendable`. On a wallet still on the legacy
      # writer the leak is exactly as it was, and stays until the migration
      # reaches it, so this keeps asserting it against the wallet it is about.
      tenant = LedgerFixtures.legacy_wallet!(unique_tenant())
      past = DateTime.add(Clock.now(), -60, :second)

      fund!(tenant, 500_000, category: :promotional, expires_at: past)
      {:ok, _} = Credits.hold(tenant, 400_000, "work:#{tenant}")
      assert {:ok, _} = Credits.expire_due()
      assert %{balance: 400_000, held: 400_000, available: 0} = Credits.balance(tenant)

      assert {:ok, %{examined: 1, released: 1}} =
               Credits.reconcile_holds(
                 older_than: cutoff(),
                 tenant: tenant,
                 reconciler: fn _hold -> :release end
               )

      assert %{balance: 400_000, held: 0, available: 400_000} = Credits.balance(tenant)
      assert {:ok, _} = Credits.debit(tenant, 400_000, "after-expiry:#{tenant}")
      assert %{balance: 0, promotional: 0} = Credits.balance(tenant)
    end
  end

  describe "what stops a hold being closed twice" do
    test "the (kind, reference) unique index refuses a second settle row" do
      # The positive half of the control below: the index is real, this test can
      # see it, and it names the constraint by name.
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      {:ok, _} = Credits.settle("j:#{tenant}", 100_000)

      assert {:error, changeset} = insert_entry(tenant, :settle, "j:#{tenant}")
      assert errors_on(changeset)[:reference]
    end

    test "and permits a release row beside a settle row for the same reference" do
      # The layer that is NOT there. `(kind, reference)` is unique, but a
      # `:settle` and a `:release` for one hold differ in `kind`, so the index
      # has nothing to say about a hold that is both settled and released.
      #
      # This is why the race in `AuroraMeter.CreditsReconcileConcurrencyTest`
      # has exactly one layer under it: the `FOR UPDATE` on the hold row in
      # `Ledger.pending_hold/3` and the `status = 'pending'` re-read inside it.
      # No constraint is standing behind them, and there is no check constraint
      # on `aurora_meter_credit_balances.held` either, so `held` would simply go
      # negative (open-findings.md X160's shape, recorded for this unit in
      # docs/evidence/v1/phase-05/05b-race-proofs.md).
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 400_000, "j:#{tenant}")
      {:ok, _} = Credits.settle("j:#{tenant}", 100_000)

      assert {:ok, %CreditTransaction{kind: :release}} =
               insert_entry(tenant, :release, "j:#{tenant}")
    end
  end

  describe "pending_holds/1" do
    test "scopes to :tenant" do
      a = unique_tenant()
      b = unique_tenant()
      fund!(a, @dollar)
      fund!(b, @dollar)
      hold!(a, 100_000, "j:#{a}")
      hold!(b, 100_000, "j:#{b}")

      assert [%CreditTransaction{tenant_key: ^a}] =
               Credits.pending_holds(older_than: cutoff(), tenant: a)

      assert [%CreditTransaction{tenant_key: ^b}] =
               Credits.pending_holds(older_than: cutoff(), tenant: b)
    end

    test "orders by (inserted_at, id) and pages without skipping same-microsecond rows" do
      tenant = unique_tenant()
      at = ~U[2026-03-01 00:00:00.000000Z]
      cutoff = DateTime.add(at, 1, :second)

      # Three holds sharing one `inserted_at` to the microsecond. Under
      # `order_by: [asc: :inserted_at]` alone their order is whatever the plan
      # happens to produce, so a `limit: 1` page could return the same row twice
      # and never return the third at all.
      for i <- 1..3, do: insert_hold!(tenant, 100_000, "j#{i}:#{tenant}", at)

      stamps = Credits.pending_holds(older_than: cutoff, tenant: tenant)
      assert stamps |> Enum.map(& &1.inserted_at) |> Enum.uniq() |> length() == 1

      seen = page(tenant, cutoff, nil, [])

      assert length(seen) == 3
      assert Enum.uniq(seen) == seen
      assert Enum.sort(seen) == Enum.sort(Enum.map(1..3, &"j#{&1}:#{tenant}"))

      # And the order the pages came back in is the order one unpaged read gives.
      assert seen == Enum.map(stamps, & &1.reference)
    end

    test "still requires :older_than" do
      assert_raise KeyError, fn -> Credits.pending_holds([]) end
    end

    test "still matches :reference_prefix as a prefix" do
      tenant = unique_tenant()
      fund!(tenant, @dollar)
      hold!(tenant, 100_000, "doc:1:#{tenant}")
      hold!(tenant, 100_000, "img:1:#{tenant}")

      assert [%CreditTransaction{reference: "doc:1:" <> _}] =
               Credits.pending_holds(
                 older_than: cutoff(),
                 tenant: tenant,
                 reference_prefix: "doc:"
               )
    end
  end

  # A ledger entry written straight past the ledger, so a test can ask the
  # database what it would and would not have refused.
  defp insert_entry(tenant, kind, reference) do
    %CreditTransaction{}
    |> Ecto.Changeset.change(%{
      tenant_key: tenant,
      kind: kind,
      amount: 0,
      held_delta: 0,
      balance_after: 0,
      held_after: 0,
      promotional_after: 0,
      reference: reference,
      metadata: %{}
    })
    |> Ecto.Changeset.unique_constraint([:kind, :reference],
      name: :aurora_meter_credit_transactions_kind_reference_index,
      error_key: :reference
    )
    |> TestRepo.insert()
  end

  defp errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {message, _opts} -> message end)
  end

  # One hold per page, resuming from the previous page's last row.
  defp page(tenant, at, after_cursor, acc) do
    opts = [older_than: at, tenant: tenant, limit: 1]
    opts = if after_cursor, do: Keyword.put(opts, :after, after_cursor), else: opts

    case Credits.pending_holds(opts) do
      [] -> Enum.reverse(acc)
      [row] -> page(tenant, at, {row.inserted_at, row.id}, [row.reference | acc])
    end
  end
end
